## Modelos Supervisados Avanzados

In [29]:
import pandas as pd
import numpy as np
import mlflow

from sklearn.ensemble import StackingClassifier, BaggingClassifier, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import VotingClassifier, StackingClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

In [3]:
import dagshub
dagshub.init(repo_owner='davidrodriguez2712',
             repo_name='ml-2-modulo',
             mlflow=True)

Accessing as davidrodriguez2712

Initialized MLflow to track repo "davidrodriguez2712/ml-2-modulo"

Repository davidrodriguez2712/ml-2-modulo initialized!

## Baseline

In [5]:
df = pd.read_csv("../data/raw/hotel_bookings.csv")
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [39]:
FEATURES = ["lead_time", "stays_in_week_nights", "children", "adr", "booking_changes"]

In [40]:
# FEATURES = ["lead_time", "stays_in_week_nights", "children", "adr"]
X, y = df[FEATURES], df["is_canceled"]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 100)

In [41]:
X_train.head()

        lead_time  stays_in_week_nights  children    adr  booking_changes
10716         180                     4       0.0   55.8                3
111508        112                     1       0.0  126.0                0
57246         440                     2       0.0   62.0                0
2498           47                     4       0.0   76.8                0
58175         232                     2       0.0   98.1                0

In [8]:
mlflow.set_tracking_uri("https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow")

In [9]:
mlflow.create_experiment("DSRP - Booking Clase 14 Julio")

'1'

In [10]:
mlflow.set_experiment("DSRP - Booking Clase 14 Julio")

<Experiment: artifact_location='mlflow-artifacts:/6c8641e9c23f4c40bc83869385c7ffeb', creation_time=1775924465349, experiment_id='1', last_update_time=1775924465349, lifecycle_stage='active', name='DSRP - Booking Clase 14 Julio', tags={}, trace_location=None, workspace='default'>

### Dummy Classifier

In [42]:
mlflow.autolog()

with mlflow.start_run(run_name = "Baseline - Dummy Classifier - Con Métricas") as run:
    algorithm = DummyClassifier(strategy = "most_frequent")
    algorithm.fit(X_train, y_train)

    predictions = algorithm.predict(X_test)
    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)

    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:09:58 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2026/04/12 11:09:58 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2026/04/12 11:09:58 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2026/04/12 11:10:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:10:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
2026/04/12 11:10:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run Baseline - Dummy Classifier - Con Métricas at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/305f1b95e3394b82b7afcbce85b0875b
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### Regresión Logística

In [43]:
with mlflow.start_run(run_name = "Regresión Logística") as run:
    algorithm = LogisticRegression()
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("reg_logistica", algorithm)
        ]
    )
    pipeline.fit(X_train, y_train)

    predictions = pipeline.predict(X_test)
    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)

    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:10:18 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:10:18 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:10:23 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:10:36 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run Regresión Logística at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/5bd6b3513a9b4ef0bb97fe3471319610
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### Emsemble : Bagging 1

In [44]:
with mlflow.start_run(run_name = "Bagging") as run:
    algorithm = BaggingClassifier()
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("bagging", algorithm)
        ]
    )
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)
    
    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:10:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:10:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:10:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:11:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run Bagging at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/67d612f4d18046228fc9c4d0ed6a9432
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### RandomForest

In [45]:
with mlflow.start_run(run_name = "Random Forest") as run:
    algorithm = RandomForestClassifier()
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("rf", algorithm)
        ]
    )
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)
    
    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:11:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:11:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:11:26 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:19:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run Random Forest at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/556a809f39c94417877a7e20bab37c85
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### Ensamble 3: XGBoost

In [46]:
with mlflow.start_run(run_name = "XGBoost") as run:
    algorithm = XGBClassifier()
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("xgboost", algorithm)
        ]
    )
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)
    
    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:19:57 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:19:57 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:20:00 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:20:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run XGBoost at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/dfdc80706d9d4ab2b07196d39d065f6d
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### Ensamble 4

In [47]:
with mlflow.start_run(run_name = "LGBM") as run:
    algorithm = LGBMClassifier()
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("lgbm", algorithm)
        ]
    )
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)
    
    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:20:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

[LightGBM] [Info] Number of positive: 33167, number of negative: 56375
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000739 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 555
[LightGBM] [Info] Number of data points in the train set: 89542, number of used features: 5
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.370407 -> initscore=-0.530470
[LightGBM] [Info] Start training from score -0.530470

2026/04/12 11:20:16 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:20:21 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:20:34 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run LGBM at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/3fd2e7208a18458ba96009c24c84afd1
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### Catboost

In [48]:
with mlflow.start_run(run_name = "Catboost") as run:
    algorithm = CatBoostClassifier()
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("catboost", algorithm)
        ]
    )
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)
    
    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:20:43 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

Learning rate set to 0.070218
0:	learn: 0.6738107	total: 5.15ms	remaining: 5.15s
1:	learn: 0.6577171	total: 8.39ms	remaining: 4.19s
2:	learn: 0.6435684	total: 12.2ms	remaining: 4.07s
3:	learn: 0.6321459	total: 15.6ms	remaining: 3.9s
4:	learn: 0.6222569	total: 18.8ms	remaining: 3.75s
5:	learn: 0.6135038	total: 22.2ms	remaining: 3.67s
6:	learn: 0.6061515	total: 25.5ms	remaining: 3.61s
7:	learn: 0.5998937	total: 29.1ms	remaining: 3.6s
8:	learn: 0.5941178	total: 32.5ms	remaining: 3.58s
9:	learn: 0.5893167	total: 36.2ms	remaining: 3.59s
10:	learn: 0.5856666	total: 39.8ms	remaining: 3.58s
11:	learn: 0.5821017	total: 43.1ms	remaining: 3.55s
12:	learn: 0.5786853	total: 46.4ms	remaining: 3.52s
13:	learn: 0.5756694	total: 49.8ms	remaining: 3.51s
14:	learn: 0.5733002	total: 53.4ms	remaining: 3.5s
15:	learn: 0.5706374	total: 57ms	remaining: 3.5s
16:	learn: 0.5683691	total: 60.2ms	remaining: 3.48s
17:	learn: 0.5667672	total: 63.7ms	remaining: 3.48s
18:	learn: 0.5653223	total: 66.6ms	remaining: 3.44s
19:	learn: 0.5641410	total: 70.3ms	remaining: 3.45s
20:	learn: 0.5631459	total: 73.5ms	remaining: 3.42s
21:	learn: 0.5618240	total: 76.9ms	remaining: 3.42s
22:	learn: 0.5608909	total: 80.2ms	remaining: 3.4s
23:	learn: 0.5599047	total: 83.4ms	remaining: 3.39s
24:	learn: 0.5586703	total: 86.4ms	remaining: 3.37s
25:	learn: 0.5582174	total: 89.8ms	remaining: 3.37s
26:	learn: 0.5573847	total: 92.7ms	remaining: 3.34s
27:	learn: 0.5568440	total: 95.9ms	remaining: 3.33s
28:	learn: 0.5559781	total: 99.1ms	remaining: 3.32s
29:	learn: 0.5551893	total: 102ms	remaining: 3.31s
30:	learn: 0.5546451	total: 106ms	remaining: 3.31s
31:	learn: 0.5543225	total: 109ms	remaining: 3.3s
32:	learn: 0.5540673	total: 112ms	remaining: 3.29s
33:	learn: 0.5535602	total: 115ms	remaining: 3.27s
34:	learn: 0.5533113	total: 119ms	remaining: 3.27s
35:	learn: 0.5529834	total: 122ms	remaining: 3.26s
36:	learn: 0.5523031	total: 125ms	remaining: 3.25s
37:	learn: 0.5515118	total: 128ms	remaining: 3.25s
38:	learn: 0.5508521	total: 132ms	remaining: 3.25s
39:	learn: 0.5506638	total: 135ms	remaining: 3.25s
40:	learn: 0.5503932	total: 139ms	remaining: 3.24s
41:	learn: 0.5501778	total: 142ms	remaining: 3.24s
42:	learn: 0.5497177	total: 145ms	remaining: 3.23s
43:	learn: 0.5494046	total: 148ms	remaining: 3.22s
44:	learn: 0.5489604	total: 152ms	remaining: 3.22s
45:	learn: 0.5487134	total: 155ms	remaining: 3.22s
46:	learn: 0.5483701	total: 158ms	remaining: 3.21s
47:	learn: 0.5479913	total: 162ms	remaining: 3.21s
48:	learn: 0.5476697	total: 165ms	remaining: 3.2s
49:	learn: 0.5473737	total: 168ms	remaining: 3.19s
50:	learn: 0.5472517	total: 171ms	remaining: 3.19s
51:	learn: 0.5468606	total: 175ms	remaining: 3.18s
52:	learn: 0.5466808	total: 178ms	remaining: 3.17s
53:	learn: 0.5463336	total: 181ms	remaining: 3.17s
54:	learn: 0.5460631	total: 184ms	remaining: 3.17s
55:	learn: 0.5460109	total: 188ms	remaining: 3.17s
56:	learn: 0.5454197	total: 191ms	remaining: 3.16s
57:	learn: 0.5451444	total: 195ms	remaining: 3.16s
58:	learn: 0.5450418	total: 198ms	remaining: 3.16s
59:	learn: 0.5448389	total: 202ms	remaining: 3.16s
60:	learn: 0.5446956	total: 205ms	remaining: 3.16s
61:	learn: 0.5442598	total: 208ms	remaining: 3.15s
62:	learn: 0.5439911	total: 212ms	remaining: 3.15s
63:	learn: 0.5439087	total: 215ms	remaining: 3.15s
64:	learn: 0.5436263	total: 218ms	remaining: 3.14s
65:	learn: 0.5435296	total: 222ms	remaining: 3.14s
66:	learn: 0.5434358	total: 225ms	remaining: 3.14s
67:	learn: 0.5433243	total: 228ms	remaining: 3.13s
68:	learn: 0.5429458	total: 232ms	remaining: 3.13s
69:	learn: 0.5428333	total: 235ms	remaining: 3.12s
70:	learn: 0.5426788	total: 238ms	remaining: 3.12s
71:	learn: 0.5425817	total: 242ms	remaining: 3.12s
72:	learn: 0.5421866	total: 245ms	remaining: 3.11s
73:	learn: 0.5420961	total: 249ms	remaining: 3.11s
74:	learn: 0.5420396	total: 252ms	remaining: 3.11s
75:	learn: 0.5418313	total: 255ms	remaining: 3.1s
76:	learn: 0.5416199	total: 258ms	remaining: 3.09s
77:	learn: 0.5414986	total: 261ms	remaining: 3.08s
78:	learn: 0.5412573	total: 264ms	remaining: 3.08s
79:	learn: 0.5411249	total: 267ms	remaining: 3.07s
80:	learn: 0.5408038	total: 271ms	remaining: 3.07s
81:	learn: 0.5406636	total: 274ms	remaining: 3.07s
82:	learn: 0.5404834	total: 277ms	remaining: 3.06s
83:	learn: 0.5403061	total: 281ms	remaining: 3.06s
84:	learn: 0.5402357	total: 284ms	remaining: 3.06s
85:	learn: 0.5397903	total: 287ms	remaining: 3.05s
86:	learn: 0.5395818	total: 291ms	remaining: 3.05s
87:	learn: 0.5395097	total: 294ms	remaining: 3.04s
88:	learn: 0.5391467	total: 297ms	remaining: 3.04s
89:	learn: 0.5390145	total: 301ms	remaining: 3.04s
90:	learn: 0.5386672	total: 304ms	remaining: 3.04s
91:	learn: 0.5384415	total: 307ms	remaining: 3.03s
92:	learn: 0.5382380	total: 310ms	remaining: 3.02s
93:	learn: 0.5381863	total: 313ms	remaining: 3.02s
94:	learn: 0.5380044	total: 317ms	remaining: 3.02s
95:	learn: 0.5379459	total: 320ms	remaining: 3.02s
96:	learn: 0.5378191	total: 324ms	remaining: 3.01s
97:	learn: 0.5377368	total: 327ms	remaining: 3.01s
98:	learn: 0.5376021	total: 330ms	remaining: 3s
99:	learn: 0.5374685	total: 334ms	remaining: 3s
100:	learn: 0.5373199	total: 337ms	remaining: 3s
101:	learn: 0.5372167	total: 340ms	remaining: 2.99s
102:	learn: 0.5370365	total: 343ms	remaining: 2.99s
103:	learn: 0.5369342	total: 346ms	remaining: 2.98s
104:	learn: 0.5368719	total: 350ms	remaining: 2.98s
105:	learn: 0.5367660	total: 353ms	remaining: 2.98s
106:	learn: 0.5366967	total: 356ms	remaining: 2.98s
107:	learn: 0.5364545	total: 360ms	remaining: 2.97s
108:	learn: 0.5362580	total: 363ms	remaining: 2.96s
109:	learn: 0.5361734	total: 366ms	remaining: 2.96s
110:	learn: 0.5359874	total: 369ms	remaining: 2.95s
111:	learn: 0.5359660	total: 372ms	remaining: 2.95s
112:	learn: 0.5357150	total: 375ms	remaining: 2.94s
113:	learn: 0.5355980	total: 379ms	remaining: 2.94s
114:	learn: 0.5354281	total: 382ms	remaining: 2.94s
115:	learn: 0.5353798	total: 385ms	remaining: 2.94s
116:	learn: 0.5352257	total: 389ms	remaining: 2.93s
117:	learn: 0.5351851	total: 392ms	remaining: 2.93s
118:	learn: 0.5349484	total: 395ms	remaining: 2.92s
119:	learn: 0.5347588	total: 399ms	remaining: 2.92s
120:	learn: 0.5345829	total: 402ms	remaining: 2.92s
121:	learn: 0.5344015	total: 405ms	remaining: 2.92s
122:	learn: 0.5341694	total: 409ms	remaining: 2.91s
123:	learn: 0.5339794	total: 412ms	remaining: 2.91s
124:	learn: 0.5339310	total: 415ms	remaining: 2.91s
125:	learn: 0.5338830	total: 419ms	remaining: 2.9s
126:	learn: 0.5337809	total: 422ms	remaining: 2.9s
127:	learn: 0.5337063	total: 426ms	remaining: 2.9s
128:	learn: 0.5336765	total: 429ms	remaining: 2.9s
129:	learn: 0.5336251	total: 433ms	remaining: 2.9s
130:	learn: 0.5333297	total: 436ms	remaining: 2.9s
131:	learn: 0.5332695	total: 440ms	remaining: 2.89s
132:	learn: 0.5329141	total: 443ms	remaining: 2.89s
133:	learn: 0.5328899	total: 446ms	remaining: 2.88s
134:	learn: 0.5328678	total: 450ms	remaining: 2.88s
135:	learn: 0.5327968	total: 453ms	remaining: 2.88s
136:	learn: 0.5326215	total: 456ms	remaining: 2.88s
137:	learn: 0.5325836	total: 460ms	remaining: 2.87s
138:	learn: 0.5324896	total: 463ms	remaining: 2.87s
139:	learn: 0.5324247	total: 466ms	remaining: 2.87s
140:	learn: 0.5323806	total: 470ms	remaining: 2.86s
141:	learn: 0.5321852	total: 473ms	remaining: 2.86s
142:	learn: 0.5320983	total: 477ms	remaining: 2.86s
143:	learn: 0.5318958	total: 480ms	remaining: 2.85s
144:	learn: 0.5318458	total: 484ms	remaining: 2.85s
145:	learn: 0.5317970	total: 487ms	remaining: 2.85s
146:	learn: 0.5315150	total: 491ms	remaining: 2.85s
147:	learn: 0.5312856	total: 494ms	remaining: 2.84s
148:	learn: 0.5309869	total: 497ms	remaining: 2.84s
149:	learn: 0.5308861	total: 501ms	remaining: 2.84s
150:	learn: 0.5308428	total: 504ms	remaining: 2.84s
151:	learn: 0.5307694	total: 508ms	remaining: 2.83s
152:	learn: 0.5307060	total: 511ms	remaining: 2.83s
153:	learn: 0.5306848	total: 515ms	remaining: 2.83s
154:	learn: 0.5304849	total: 518ms	remaining: 2.82s
155:	learn: 0.5303018	total: 521ms	remaining: 2.82s
156:	learn: 0.5300803	total: 525ms	remaining: 2.82s
157:	learn: 0.5299034	total: 529ms	remaining: 2.82s
158:	learn: 0.5296628	total: 532ms	remaining: 2.82s
159:	learn: 0.5295286	total: 536ms	remaining: 2.81s
160:	learn: 0.5294176	total: 539ms	remaining: 2.81s
161:	learn: 0.5292346	total: 543ms	remaining: 2.81s
162:	learn: 0.5291623	total: 546ms	remaining: 2.8s
163:	learn: 0.5289835	total: 550ms	remaining: 2.8s
164:	learn: 0.5289236	total: 553ms	remaining: 2.8s
165:	learn: 0.5288327	total: 556ms	remaining: 2.79s
166:	learn: 0.5286664	total: 560ms	remaining: 2.79s
167:	learn: 0.5285878	total: 564ms	remaining: 2.79s
168:	learn: 0.5285416	total: 567ms	remaining: 2.79s
169:	learn: 0.5283516	total: 570ms	remaining: 2.78s
170:	learn: 0.5282968	total: 573ms	remaining: 2.78s
171:	learn: 0.5282452	total: 577ms	remaining: 2.77s
172:	learn: 0.5280301	total: 580ms	remaining: 2.77s
173:	learn: 0.5278876	total: 584ms	remaining: 2.77s
174:	learn: 0.5276559	total: 587ms	remaining: 2.77s
175:	learn: 0.5275279	total: 590ms	remaining: 2.76s
176:	learn: 0.5274036	total: 594ms	remaining: 2.76s
177:	learn: 0.5272711	total: 597ms	remaining: 2.76s
178:	learn: 0.5270226	total: 601ms	remaining: 2.76s
179:	learn: 0.5269950	total: 605ms	remaining: 2.75s
180:	learn: 0.5268308	total: 608ms	remaining: 2.75s
181:	learn: 0.5266779	total: 612ms	remaining: 2.75s
182:	learn: 0.5264732	total: 616ms	remaining: 2.75s
183:	learn: 0.5263815	total: 619ms	remaining: 2.74s
184:	learn: 0.5261524	total: 622ms	remaining: 2.74s
185:	learn: 0.5260501	total: 625ms	remaining: 2.74s
186:	learn: 0.5258866	total: 629ms	remaining: 2.73s
187:	learn: 0.5256008	total: 632ms	remaining: 2.73s
188:	learn: 0.5254093	total: 636ms	remaining: 2.73s
189:	learn: 0.5252663	total: 639ms	remaining: 2.73s
190:	learn: 0.5251440	total: 643ms	remaining: 2.72s
191:	learn: 0.5250158	total: 646ms	remaining: 2.72s
192:	learn: 0.5249114	total: 650ms	remaining: 2.71s
193:	learn: 0.5247453	total: 653ms	remaining: 2.71s
194:	learn: 0.5246752	total: 656ms	remaining: 2.71s
195:	learn: 0.5244250	total: 660ms	remaining: 2.71s
196:	learn: 0.5243375	total: 663ms	remaining: 2.7s
197:	learn: 0.5242522	total: 667ms	remaining: 2.7s
198:	learn: 0.5241577	total: 670ms	remaining: 2.7s
199:	learn: 0.5240787	total: 674ms	remaining: 2.69s
200:	learn: 0.5239741	total: 677ms	remaining: 2.69s
201:	learn: 0.5238183	total: 681ms	remaining: 2.69s
202:	learn: 0.5236766	total: 684ms	remaining: 2.69s
203:	learn: 0.5235352	total: 688ms	remaining: 2.68s
204:	learn: 0.5233945	total: 691ms	remaining: 2.68s
205:	learn: 0.5232546	total: 695ms	remaining: 2.68s
206:	learn: 0.5230454	total: 698ms	remaining: 2.67s
207:	learn: 0.5229536	total: 701ms	remaining: 2.67s
208:	learn: 0.5227056	total: 705ms	remaining: 2.67s
209:	learn: 0.5225294	total: 708ms	remaining: 2.66s
210:	learn: 0.5224116	total: 712ms	remaining: 2.66s
211:	learn: 0.5221831	total: 716ms	remaining: 2.66s
212:	learn: 0.5220323	total: 719ms	remaining: 2.66s
213:	learn: 0.5219855	total: 722ms	remaining: 2.65s
214:	learn: 0.5219285	total: 726ms	remaining: 2.65s
215:	learn: 0.5218675	total: 729ms	remaining: 2.65s
216:	learn: 0.5216811	total: 733ms	remaining: 2.64s
217:	learn: 0.5215916	total: 736ms	remaining: 2.64s
218:	learn: 0.5214674	total: 739ms	remaining: 2.64s
219:	learn: 0.5213997	total: 743ms	remaining: 2.63s
220:	learn: 0.5212905	total: 747ms	remaining: 2.63s
221:	learn: 0.5211581	total: 750ms	remaining: 2.63s
222:	learn: 0.5210843	total: 753ms	remaining: 2.62s
223:	learn: 0.5209140	total: 757ms	remaining: 2.62s
224:	learn: 0.5208204	total: 760ms	remaining: 2.62s
225:	learn: 0.5206668	total: 764ms	remaining: 2.62s
226:	learn: 0.5204637	total: 768ms	remaining: 2.61s
227:	learn: 0.5203735	total: 771ms	remaining: 2.61s
228:	learn: 0.5202461	total: 775ms	remaining: 2.61s
229:	learn: 0.5201411	total: 778ms	remaining: 2.6s
230:	learn: 0.5200951	total: 782ms	remaining: 2.6s
231:	learn: 0.5199251	total: 786ms	remaining: 2.6s
232:	learn: 0.5196606	total: 789ms	remaining: 2.6s
233:	learn: 0.5195978	total: 793ms	remaining: 2.6s
234:	learn: 0.5195306	total: 797ms	remaining: 2.59s
235:	learn: 0.5194868	total: 800ms	remaining: 2.59s
236:	learn: 0.5193511	total: 804ms	remaining: 2.59s
237:	learn: 0.5192522	total: 807ms	remaining: 2.58s
238:	learn: 0.5191186	total: 810ms	remaining: 2.58s
239:	learn: 0.5189888	total: 814ms	remaining: 2.58s
240:	learn: 0.5188789	total: 817ms	remaining: 2.57s
241:	learn: 0.5188263	total: 821ms	remaining: 2.57s
242:	learn: 0.5187082	total: 824ms	remaining: 2.57s
243:	learn: 0.5186290	total: 827ms	remaining: 2.56s
244:	learn: 0.5185630	total: 831ms	remaining: 2.56s
245:	learn: 0.5183649	total: 834ms	remaining: 2.56s
246:	learn: 0.5182405	total: 838ms	remaining: 2.55s
247:	learn: 0.5181347	total: 842ms	remaining: 2.55s
248:	learn: 0.5180941	total: 845ms	remaining: 2.55s
249:	learn: 0.5179986	total: 849ms	remaining: 2.55s
250:	learn: 0.5177729	total: 852ms	remaining: 2.54s
251:	learn: 0.5175595	total: 856ms	remaining: 2.54s
252:	learn: 0.5173605	total: 859ms	remaining: 2.54s
253:	learn: 0.5172872	total: 863ms	remaining: 2.53s
254:	learn: 0.5171869	total: 866ms	remaining: 2.53s
255:	learn: 0.5171012	total: 869ms	remaining: 2.53s
256:	learn: 0.5170473	total: 873ms	remaining: 2.52s
257:	learn: 0.5169330	total: 876ms	remaining: 2.52s
258:	learn: 0.5168371	total: 880ms	remaining: 2.52s
259:	learn: 0.5167635	total: 883ms	remaining: 2.51s
260:	learn: 0.5165662	total: 887ms	remaining: 2.51s
261:	learn: 0.5164838	total: 890ms	remaining: 2.5s
262:	learn: 0.5164583	total: 893ms	remaining: 2.5s
263:	learn: 0.5163649	total: 897ms	remaining: 2.5s
264:	learn: 0.5162891	total: 900ms	remaining: 2.5s
265:	learn: 0.5162438	total: 904ms	remaining: 2.49s
266:	learn: 0.5161543	total: 907ms	remaining: 2.49s
267:	learn: 0.5160240	total: 911ms	remaining: 2.49s
268:	learn: 0.5157750	total: 914ms	remaining: 2.48s
269:	learn: 0.5156623	total: 918ms	remaining: 2.48s
270:	learn: 0.5156136	total: 921ms	remaining: 2.48s
271:	learn: 0.5154161	total: 925ms	remaining: 2.48s
272:	learn: 0.5153093	total: 929ms	remaining: 2.47s
273:	learn: 0.5152120	total: 932ms	remaining: 2.47s
274:	learn: 0.5151480	total: 936ms	remaining: 2.47s
275:	learn: 0.5150466	total: 939ms	remaining: 2.46s
276:	learn: 0.5149717	total: 945ms	remaining: 2.46s
277:	learn: 0.5149055	total: 950ms	remaining: 2.47s
278:	learn: 0.5146734	total: 954ms	remaining: 2.46s
279:	learn: 0.5145622	total: 957ms	remaining: 2.46s
280:	learn: 0.5145179	total: 961ms	remaining: 2.46s
281:	learn: 0.5143120	total: 965ms	remaining: 2.46s
282:	learn: 0.5142567	total: 968ms	remaining: 2.45s
283:	learn: 0.5141674	total: 972ms	remaining: 2.45s
284:	learn: 0.5138584	total: 975ms	remaining: 2.45s
285:	learn: 0.5136946	total: 979ms	remaining: 2.44s
286:	learn: 0.5135373	total: 982ms	remaining: 2.44s
287:	learn: 0.5134211	total: 986ms	remaining: 2.44s
288:	learn: 0.5133091	total: 990ms	remaining: 2.43s
289:	learn: 0.5132147	total: 993ms	remaining: 2.43s
290:	learn: 0.5131165	total: 997ms	remaining: 2.43s
291:	learn: 0.5130303	total: 1s	remaining: 2.43s
292:	learn: 0.5129591	total: 1s	remaining: 2.42s
293:	learn: 0.5128433	total: 1.01s	remaining: 2.42s
294:	learn: 0.5127782	total: 1.01s	remaining: 2.42s
295:	learn: 0.5127264	total: 1.01s	remaining: 2.42s
296:	learn: 0.5126284	total: 1.02s	remaining: 2.41s
297:	learn: 0.5125577	total: 1.02s	remaining: 2.41s
298:	learn: 0.5124790	total: 1.02s	remaining: 2.4s
299:	learn: 0.5123628	total: 1.03s	remaining: 2.4s
300:	learn: 0.5123144	total: 1.03s	remaining: 2.4s
301:	learn: 0.5122488	total: 1.03s	remaining: 2.39s
302:	learn: 0.5122018	total: 1.04s	remaining: 2.39s
303:	learn: 0.5120993	total: 1.04s	remaining: 2.39s
304:	learn: 0.5119469	total: 1.04s	remaining: 2.38s
305:	learn: 0.5118851	total: 1.05s	remaining: 2.38s
306:	learn: 0.5118100	total: 1.05s	remaining: 2.38s
307:	learn: 0.5116833	total: 1.06s	remaining: 2.37s
308:	learn: 0.5115890	total: 1.06s	remaining: 2.37s
309:	learn: 0.5114555	total: 1.06s	remaining: 2.37s
310:	learn: 0.5113136	total: 1.07s	remaining: 2.36s
311:	learn: 0.5112220	total: 1.07s	remaining: 2.36s
312:	learn: 0.5110947	total: 1.07s	remaining: 2.36s
313:	learn: 0.5109252	total: 1.08s	remaining: 2.35s
314:	learn: 0.5108456	total: 1.08s	remaining: 2.35s
315:	learn: 0.5107625	total: 1.08s	remaining: 2.35s
316:	learn: 0.5106565	total: 1.09s	remaining: 2.34s
317:	learn: 0.5103883	total: 1.09s	remaining: 2.34s
318:	learn: 0.5102217	total: 1.09s	remaining: 2.34s
319:	learn: 0.5101590	total: 1.1s	remaining: 2.33s
320:	learn: 0.5100822	total: 1.1s	remaining: 2.33s
321:	learn: 0.5099999	total: 1.1s	remaining: 2.33s
322:	learn: 0.5099383	total: 1.11s	remaining: 2.32s
323:	learn: 0.5098506	total: 1.11s	remaining: 2.32s
324:	learn: 0.5097007	total: 1.12s	remaining: 2.32s
325:	learn: 0.5095294	total: 1.12s	remaining: 2.31s
326:	learn: 0.5094909	total: 1.12s	remaining: 2.31s
327:	learn: 0.5094469	total: 1.13s	remaining: 2.31s
328:	learn: 0.5093579	total: 1.13s	remaining: 2.31s
329:	learn: 0.5091998	total: 1.13s	remaining: 2.3s
330:	learn: 0.5090303	total: 1.14s	remaining: 2.3s
331:	learn: 0.5089854	total: 1.14s	remaining: 2.29s
332:	learn: 0.5087932	total: 1.14s	remaining: 2.29s
333:	learn: 0.5087195	total: 1.15s	remaining: 2.29s
334:	learn: 0.5085844	total: 1.15s	remaining: 2.29s
335:	learn: 0.5085201	total: 1.15s	remaining: 2.28s
336:	learn: 0.5084779	total: 1.16s	remaining: 2.28s
337:	learn: 0.5084452	total: 1.16s	remaining: 2.27s
338:	learn: 0.5083833	total: 1.16s	remaining: 2.27s
339:	learn: 0.5082780	total: 1.17s	remaining: 2.27s
340:	learn: 0.5081781	total: 1.17s	remaining: 2.27s
341:	learn: 0.5081241	total: 1.18s	remaining: 2.26s
342:	learn: 0.5080407	total: 1.18s	remaining: 2.26s
343:	learn: 0.5079481	total: 1.18s	remaining: 2.25s
344:	learn: 0.5078521	total: 1.19s	remaining: 2.25s
345:	learn: 0.5077417	total: 1.19s	remaining: 2.25s
346:	learn: 0.5076455	total: 1.19s	remaining: 2.24s
347:	learn: 0.5075013	total: 1.2s	remaining: 2.24s
348:	learn: 0.5074599	total: 1.2s	remaining: 2.24s
349:	learn: 0.5073286	total: 1.2s	remaining: 2.23s
350:	learn: 0.5072491	total: 1.21s	remaining: 2.23s
351:	learn: 0.5071282	total: 1.21s	remaining: 2.23s
352:	learn: 0.5071025	total: 1.21s	remaining: 2.23s
353:	learn: 0.5069892	total: 1.22s	remaining: 2.22s
354:	learn: 0.5069089	total: 1.22s	remaining: 2.22s
355:	learn: 0.5068609	total: 1.23s	remaining: 2.22s
356:	learn: 0.5068150	total: 1.23s	remaining: 2.21s
357:	learn: 0.5067168	total: 1.23s	remaining: 2.21s
358:	learn: 0.5066460	total: 1.24s	remaining: 2.21s
359:	learn: 0.5065638	total: 1.24s	remaining: 2.2s
360:	learn: 0.5063826	total: 1.24s	remaining: 2.2s
361:	learn: 0.5062679	total: 1.25s	remaining: 2.19s
362:	learn: 0.5061974	total: 1.25s	remaining: 2.19s
363:	learn: 0.5061007	total: 1.25s	remaining: 2.19s
364:	learn: 0.5060054	total: 1.26s	remaining: 2.19s
365:	learn: 0.5059738	total: 1.26s	remaining: 2.18s
366:	learn: 0.5059230	total: 1.26s	remaining: 2.18s
367:	learn: 0.5058569	total: 1.27s	remaining: 2.18s
368:	learn: 0.5057196	total: 1.27s	remaining: 2.17s
369:	learn: 0.5056482	total: 1.27s	remaining: 2.17s
370:	learn: 0.5055686	total: 1.28s	remaining: 2.17s
371:	learn: 0.5055230	total: 1.28s	remaining: 2.16s
372:	learn: 0.5054588	total: 1.28s	remaining: 2.16s
373:	learn: 0.5054096	total: 1.29s	remaining: 2.16s
374:	learn: 0.5052337	total: 1.29s	remaining: 2.15s
375:	learn: 0.5051835	total: 1.29s	remaining: 2.15s
376:	learn: 0.5051056	total: 1.3s	remaining: 2.15s
377:	learn: 0.5050269	total: 1.3s	remaining: 2.14s
378:	learn: 0.5049835	total: 1.31s	remaining: 2.14s
379:	learn: 0.5047542	total: 1.31s	remaining: 2.14s
380:	learn: 0.5046491	total: 1.31s	remaining: 2.13s
381:	learn: 0.5045834	total: 1.32s	remaining: 2.13s
382:	learn: 0.5044992	total: 1.32s	remaining: 2.13s
383:	learn: 0.5044166	total: 1.32s	remaining: 2.12s
384:	learn: 0.5044015	total: 1.33s	remaining: 2.13s
385:	learn: 0.5043303	total: 1.33s	remaining: 2.13s

2026/04/12 11:20:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

982:	learn: 0.4731129	total: 3.4s	remaining: 58.9ms
983:	learn: 0.4730574	total: 3.41s	remaining: 55.4ms
984:	learn: 0.4730315	total: 3.41s	remaining: 51.9ms
985:	learn: 0.4729988	total: 3.42s	remaining: 48.5ms
986:	learn: 0.4729595	total: 3.42s	remaining: 45.1ms
987:	learn: 0.4729184	total: 3.43s	remaining: 41.6ms
988:	learn: 0.4728849	total: 3.43s	remaining: 38.2ms
989:	learn: 0.4728505	total: 3.43s	remaining: 34.7ms
990:	learn: 0.4728105	total: 3.44s	remaining: 31.2ms
991:	learn: 0.4727905	total: 3.44s	remaining: 27.7ms
992:	learn: 0.4727780	total: 3.44s	remaining: 24.3ms
993:	learn: 0.4727527	total: 3.45s	remaining: 20.8ms
994:	learn: 0.4727179	total: 3.45s	remaining: 17.3ms
995:	learn: 0.4727011	total: 3.45s	remaining: 13.9ms
996:	learn: 0.4726649	total: 3.46s	remaining: 10.4ms
997:	learn: 0.4726213	total: 3.46s	remaining: 6.93ms
998:	learn: 0.4725722	total: 3.46s	remaining: 3.47ms
999:	learn: 0.4725412	total: 3.47s	remaining: 0us

2026/04/12 11:20:49 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:21:02 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run Catboost at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/59ace58e62d74bc4909abfbd80850601
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### Ensamble 6: Voting

In [49]:
with mlflow.start_run(run_name = "Ensamble de Votos") as run:

    
    algorithm1 = CatBoostClassifier()
    algorithm2 = RandomForestClassifier()
    algorithm3 = LGBMClassifier()

    voting_clf = VotingClassifier(
        estimators = [
            ("catboost", algorithm1),
            ("rf", algorithm2),
            ("lgbm", algorithm3),
        ],
        voting = "hard"
    )
    
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("voting", voting_clf)
        ]
    )
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)
    
    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:21:11 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

Learning rate set to 0.070218
0:	learn: 0.6738107	total: 4.75ms	remaining: 4.75s
1:	learn: 0.6577171	total: 8.26ms	remaining: 4.12s
2:	learn: 0.6435684	total: 11.7ms	remaining: 3.9s
3:	learn: 0.6321459	total: 15.1ms	remaining: 3.76s
4:	learn: 0.6222569	total: 18.4ms	remaining: 3.65s
5:	learn: 0.6135038	total: 22ms	remaining: 3.64s
6:	learn: 0.6061515	total: 25.5ms	remaining: 3.62s
7:	learn: 0.5998937	total: 29.1ms	remaining: 3.61s
8:	learn: 0.5941178	total: 33.1ms	remaining: 3.64s
9:	learn: 0.5893167	total: 36.7ms	remaining: 3.64s
10:	learn: 0.5856666	total: 40.3ms	remaining: 3.62s
11:	learn: 0.5821017	total: 43.3ms	remaining: 3.57s
12:	learn: 0.5786853	total: 47ms	remaining: 3.57s
13:	learn: 0.5756694	total: 50.5ms	remaining: 3.56s
14:	learn: 0.5733002	total: 54.6ms	remaining: 3.59s
15:	learn: 0.5706374	total: 58.5ms	remaining: 3.6s
16:	learn: 0.5683691	total: 61.8ms	remaining: 3.58s
17:	learn: 0.5667672	total: 65.6ms	remaining: 3.58s
18:	learn: 0.5653223	total: 68.9ms	remaining: 3.56s
19:	learn: 0.5641410	total: 72.8ms	remaining: 3.57s
20:	learn: 0.5631459	total: 76ms	remaining: 3.54s
21:	learn: 0.5618240	total: 79.8ms	remaining: 3.55s
22:	learn: 0.5608909	total: 83.2ms	remaining: 3.54s
23:	learn: 0.5599047	total: 86.9ms	remaining: 3.53s
24:	learn: 0.5586703	total: 90ms	remaining: 3.51s
25:	learn: 0.5582174	total: 93.9ms	remaining: 3.52s
26:	learn: 0.5573847	total: 97ms	remaining: 3.5s
27:	learn: 0.5568440	total: 100ms	remaining: 3.49s
28:	learn: 0.5559781	total: 104ms	remaining: 3.48s
29:	learn: 0.5551893	total: 107ms	remaining: 3.47s
30:	learn: 0.5546451	total: 111ms	remaining: 3.46s
31:	learn: 0.5543225	total: 114ms	remaining: 3.46s
32:	learn: 0.5540673	total: 118ms	remaining: 3.45s
33:	learn: 0.5535602	total: 121ms	remaining: 3.44s
34:	learn: 0.5533113	total: 125ms	remaining: 3.43s
35:	learn: 0.5529834	total: 128ms	remaining: 3.43s
36:	learn: 0.5523031	total: 132ms	remaining: 3.43s
37:	learn: 0.5515118	total: 135ms	remaining: 3.42s
38:	learn: 0.5508521	total: 139ms	remaining: 3.42s
39:	learn: 0.5506638	total: 142ms	remaining: 3.41s
40:	learn: 0.5503932	total: 146ms	remaining: 3.41s
41:	learn: 0.5501778	total: 149ms	remaining: 3.4s
42:	learn: 0.5497177	total: 152ms	remaining: 3.38s
43:	learn: 0.5494046	total: 156ms	remaining: 3.39s
44:	learn: 0.5489604	total: 160ms	remaining: 3.39s
45:	learn: 0.5487134	total: 163ms	remaining: 3.38s
46:	learn: 0.5483701	total: 167ms	remaining: 3.38s
47:	learn: 0.5479913	total: 170ms	remaining: 3.37s
48:	learn: 0.5476697	total: 174ms	remaining: 3.37s
49:	learn: 0.5473737	total: 177ms	remaining: 3.37s
50:	learn: 0.5472517	total: 181ms	remaining: 3.36s
51:	learn: 0.5468606	total: 185ms	remaining: 3.37s
52:	learn: 0.5466808	total: 189ms	remaining: 3.37s
53:	learn: 0.5463336	total: 192ms	remaining: 3.36s
54:	learn: 0.5460631	total: 195ms	remaining: 3.36s
55:	learn: 0.5460109	total: 199ms	remaining: 3.35s
56:	learn: 0.5454197	total: 203ms	remaining: 3.35s
57:	learn: 0.5451444	total: 206ms	remaining: 3.35s
58:	learn: 0.5450418	total: 209ms	remaining: 3.34s
59:	learn: 0.5448389	total: 213ms	remaining: 3.34s
60:	learn: 0.5446956	total: 217ms	remaining: 3.33s
61:	learn: 0.5442598	total: 220ms	remaining: 3.33s
62:	learn: 0.5439911	total: 224ms	remaining: 3.33s
63:	learn: 0.5439087	total: 227ms	remaining: 3.32s
64:	learn: 0.5436263	total: 230ms	remaining: 3.31s
65:	learn: 0.5435296	total: 234ms	remaining: 3.31s
66:	learn: 0.5434358	total: 237ms	remaining: 3.3s
67:	learn: 0.5433243	total: 240ms	remaining: 3.29s
68:	learn: 0.5429458	total: 244ms	remaining: 3.29s
69:	learn: 0.5428333	total: 247ms	remaining: 3.28s
70:	learn: 0.5426788	total: 250ms	remaining: 3.27s
71:	learn: 0.5425817	total: 254ms	remaining: 3.27s
72:	learn: 0.5421866	total: 257ms	remaining: 3.27s
73:	learn: 0.5420961	total: 262ms	remaining: 3.28s
74:	learn: 0.5420396	total: 265ms	remaining: 3.27s
75:	learn: 0.5418313	total: 269ms	remaining: 3.27s
76:	learn: 0.5416199	total: 272ms	remaining: 3.26s
77:	learn: 0.5414986	total: 275ms	remaining: 3.25s
78:	learn: 0.5412573	total: 278ms	remaining: 3.24s
79:	learn: 0.5411249	total: 282ms	remaining: 3.24s
80:	learn: 0.5408038	total: 285ms	remaining: 3.23s
81:	learn: 0.5406636	total: 288ms	remaining: 3.23s
82:	learn: 0.5404834	total: 292ms	remaining: 3.22s
83:	learn: 0.5403061	total: 295ms	remaining: 3.22s
84:	learn: 0.5402357	total: 298ms	remaining: 3.21s
85:	learn: 0.5397903	total: 302ms	remaining: 3.21s
86:	learn: 0.5395818	total: 305ms	remaining: 3.2s
87:	learn: 0.5395097	total: 308ms	remaining: 3.19s
88:	learn: 0.5391467	total: 311ms	remaining: 3.19s
89:	learn: 0.5390145	total: 315ms	remaining: 3.18s
90:	learn: 0.5386672	total: 318ms	remaining: 3.18s
91:	learn: 0.5384415	total: 321ms	remaining: 3.17s
92:	learn: 0.5382380	total: 324ms	remaining: 3.16s
93:	learn: 0.5381863	total: 328ms	remaining: 3.16s
94:	learn: 0.5380044	total: 331ms	remaining: 3.15s
95:	learn: 0.5379459	total: 334ms	remaining: 3.15s
96:	learn: 0.5378191	total: 337ms	remaining: 3.14s
97:	learn: 0.5377368	total: 340ms	remaining: 3.13s
98:	learn: 0.5376021	total: 344ms	remaining: 3.13s
99:	learn: 0.5374685	total: 347ms	remaining: 3.12s
100:	learn: 0.5373199	total: 350ms	remaining: 3.12s
101:	learn: 0.5372167	total: 353ms	remaining: 3.11s
102:	learn: 0.5370365	total: 357ms	remaining: 3.11s
103:	learn: 0.5369342	total: 360ms	remaining: 3.1s
104:	learn: 0.5368719	total: 363ms	remaining: 3.1s
105:	learn: 0.5367660	total: 367ms	remaining: 3.09s
106:	learn: 0.5366967	total: 370ms	remaining: 3.09s
107:	learn: 0.5364545	total: 373ms	remaining: 3.08s
108:	learn: 0.5362580	total: 377ms	remaining: 3.08s
109:	learn: 0.5361734	total: 381ms	remaining: 3.08s
110:	learn: 0.5359874	total: 384ms	remaining: 3.07s
111:	learn: 0.5359660	total: 387ms	remaining: 3.07s
112:	learn: 0.5357150	total: 390ms	remaining: 3.06s
113:	learn: 0.5355980	total: 394ms	remaining: 3.06s
114:	learn: 0.5354281	total: 397ms	remaining: 3.06s
115:	learn: 0.5353798	total: 401ms	remaining: 3.06s
116:	learn: 0.5352257	total: 405ms	remaining: 3.06s
117:	learn: 0.5351851	total: 408ms	remaining: 3.05s
118:	learn: 0.5349484	total: 412ms	remaining: 3.05s
119:	learn: 0.5347588	total: 415ms	remaining: 3.05s
120:	learn: 0.5345829	total: 419ms	remaining: 3.04s
121:	learn: 0.5344015	total: 422ms	remaining: 3.04s
122:	learn: 0.5341694	total: 426ms	remaining: 3.04s
123:	learn: 0.5339794	total: 430ms	remaining: 3.04s
124:	learn: 0.5339310	total: 433ms	remaining: 3.03s
125:	learn: 0.5338830	total: 437ms	remaining: 3.03s
126:	learn: 0.5337809	total: 440ms	remaining: 3.02s
127:	learn: 0.5337063	total: 443ms	remaining: 3.02s
128:	learn: 0.5336765	total: 447ms	remaining: 3.02s
129:	learn: 0.5336251	total: 450ms	remaining: 3.01s
130:	learn: 0.5333297	total: 454ms	remaining: 3.01s
131:	learn: 0.5332695	total: 457ms	remaining: 3.01s
132:	learn: 0.5329141	total: 461ms	remaining: 3.01s
133:	learn: 0.5328899	total: 464ms	remaining: 3s
134:	learn: 0.5328678	total: 468ms	remaining: 3s
135:	learn: 0.5327968	total: 471ms	remaining: 2.99s
136:	learn: 0.5326215	total: 475ms	remaining: 2.99s
137:	learn: 0.5325836	total: 478ms	remaining: 2.99s
138:	learn: 0.5324896	total: 482ms	remaining: 2.98s
139:	learn: 0.5324247	total: 485ms	remaining: 2.98s
140:	learn: 0.5323806	total: 489ms	remaining: 2.98s
141:	learn: 0.5321852	total: 492ms	remaining: 2.97s
142:	learn: 0.5320983	total: 496ms	remaining: 2.97s
143:	learn: 0.5318958	total: 499ms	remaining: 2.97s
144:	learn: 0.5318458	total: 502ms	remaining: 2.96s
145:	learn: 0.5317970	total: 506ms	remaining: 2.96s
146:	learn: 0.5315150	total: 509ms	remaining: 2.95s
147:	learn: 0.5312856	total: 513ms	remaining: 2.95s
148:	learn: 0.5309869	total: 516ms	remaining: 2.95s
149:	learn: 0.5308861	total: 520ms	remaining: 2.94s
150:	learn: 0.5308428	total: 523ms	remaining: 2.94s
151:	learn: 0.5307694	total: 526ms	remaining: 2.94s
152:	learn: 0.5307060	total: 530ms	remaining: 2.93s
153:	learn: 0.5306848	total: 533ms	remaining: 2.92s
154:	learn: 0.5304849	total: 536ms	remaining: 2.92s
155:	learn: 0.5303018	total: 539ms	remaining: 2.92s
156:	learn: 0.5300803	total: 543ms	remaining: 2.92s
157:	learn: 0.5299034	total: 546ms	remaining: 2.91s
158:	learn: 0.5296628	total: 549ms	remaining: 2.91s
159:	learn: 0.5295286	total: 553ms	remaining: 2.9s
160:	learn: 0.5294176	total: 556ms	remaining: 2.9s
161:	learn: 0.5292346	total: 559ms	remaining: 2.89s
162:	learn: 0.5291623	total: 562ms	remaining: 2.89s
163:	learn: 0.5289835	total: 566ms	remaining: 2.88s
164:	learn: 0.5289236	total: 569ms	remaining: 2.88s
165:	learn: 0.5288327	total: 572ms	remaining: 2.88s
166:	learn: 0.5286664	total: 576ms	remaining: 2.87s
167:	learn: 0.5285878	total: 579ms	remaining: 2.87s
168:	learn: 0.5285416	total: 582ms	remaining: 2.86s
169:	learn: 0.5283516	total: 586ms	remaining: 2.86s
170:	learn: 0.5282968	total: 589ms	remaining: 2.86s
171:	learn: 0.5282452	total: 593ms	remaining: 2.85s
172:	learn: 0.5280301	total: 596ms	remaining: 2.85s
173:	learn: 0.5278876	total: 599ms	remaining: 2.84s
174:	learn: 0.5276559	total: 603ms	remaining: 2.84s
175:	learn: 0.5275279	total: 606ms	remaining: 2.84s
176:	learn: 0.5274036	total: 610ms	remaining: 2.83s
177:	learn: 0.5272711	total: 613ms	remaining: 2.83s
178:	learn: 0.5270226	total: 616ms	remaining: 2.83s
179:	learn: 0.5269950	total: 619ms	remaining: 2.82s
180:	learn: 0.5268308	total: 622ms	remaining: 2.82s
181:	learn: 0.5266779	total: 626ms	remaining: 2.81s
182:	learn: 0.5264732	total: 629ms	remaining: 2.81s
183:	learn: 0.5263815	total: 632ms	remaining: 2.8s
184:	learn: 0.5261524	total: 636ms	remaining: 2.8s
185:	learn: 0.5260501	total: 639ms	remaining: 2.8s
186:	learn: 0.5258866	total: 642ms	remaining: 2.79s
187:	learn: 0.5256008	total: 645ms	remaining: 2.79s
188:	learn: 0.5254093	total: 649ms	remaining: 2.78s
189:	learn: 0.5252663	total: 652ms	remaining: 2.78s
190:	learn: 0.5251440	total: 655ms	remaining: 2.77s
191:	learn: 0.5250158	total: 658ms	remaining: 2.77s
192:	learn: 0.5249114	total: 662ms	remaining: 2.77s
193:	learn: 0.5247453	total: 665ms	remaining: 2.76s
194:	learn: 0.5246752	total: 668ms	remaining: 2.76s
195:	learn: 0.5244250	total: 672ms	remaining: 2.76s
196:	learn: 0.5243375	total: 675ms	remaining: 2.75s
197:	learn: 0.5242522	total: 678ms	remaining: 2.75s
198:	learn: 0.5241577	total: 682ms	remaining: 2.74s
199:	learn: 0.5240787	total: 685ms	remaining: 2.74s
200:	learn: 0.5239741	total: 688ms	remaining: 2.74s
201:	learn: 0.5238183	total: 692ms	remaining: 2.73s
202:	learn: 0.5236766	total: 695ms	remaining: 2.73s
203:	learn: 0.5235352	total: 698ms	remaining: 2.72s
204:	learn: 0.5233945	total: 701ms	remaining: 2.72s
205:	learn: 0.5232546	total: 705ms	remaining: 2.71s
206:	learn: 0.5230454	total: 708ms	remaining: 2.71s
207:	learn: 0.5229536	total: 711ms	remaining: 2.71s
208:	learn: 0.5227056	total: 715ms	remaining: 2.71s
209:	learn: 0.5225294	total: 718ms	remaining: 2.7s
210:	learn: 0.5224116	total: 721ms	remaining: 2.7s
211:	learn: 0.5221831	total: 725ms	remaining: 2.69s
212:	learn: 0.5220323	total: 728ms	remaining: 2.69s
213:	learn: 0.5219855	total: 731ms	remaining: 2.69s
214:	learn: 0.5219285	total: 734ms	remaining: 2.68s
215:	learn: 0.5218675	total: 738ms	remaining: 2.68s
216:	learn: 0.5216811	total: 741ms	remaining: 2.67s
217:	learn: 0.5215916	total: 744ms	remaining: 2.67s
218:	learn: 0.5214674	total: 747ms	remaining: 2.66s
219:	learn: 0.5213997	total: 750ms	remaining: 2.66s
220:	learn: 0.5212905	total: 754ms	remaining: 2.66s
221:	learn: 0.5211581	total: 757ms	remaining: 2.65s
222:	learn: 0.5210843	total: 760ms	remaining: 2.65s
223:	learn: 0.5209140	total: 763ms	remaining: 2.64s
224:	learn: 0.5208204	total: 767ms	remaining: 2.64s
225:	learn: 0.5206668	total: 770ms	remaining: 2.64s
226:	learn: 0.5204637	total: 774ms	remaining: 2.63s
227:	learn: 0.5203735	total: 777ms	remaining: 2.63s
228:	learn: 0.5202461	total: 780ms	remaining: 2.63s
229:	learn: 0.5201411	total: 784ms	remaining: 2.62s
230:	learn: 0.5200951	total: 787ms	remaining: 2.62s
231:	learn: 0.5199251	total: 791ms	remaining: 2.62s
232:	learn: 0.5196606	total: 794ms	remaining: 2.61s
233:	learn: 0.5195978	total: 798ms	remaining: 2.61s
234:	learn: 0.5195306	total: 801ms	remaining: 2.61s
235:	learn: 0.5194868	total: 804ms	remaining: 2.6s
236:	learn: 0.5193511	total: 808ms	remaining: 2.6s
237:	learn: 0.5192522	total: 811ms	remaining: 2.6s
238:	learn: 0.5191186	total: 814ms	remaining: 2.59s
239:	learn: 0.5189888	total: 818ms	remaining: 2.59s
240:	learn: 0.5188789	total: 821ms	remaining: 2.58s
241:	learn: 0.5188263	total: 824ms	remaining: 2.58s
242:	learn: 0.5187082	total: 827ms	remaining: 2.58s
243:	learn: 0.5186290	total: 831ms	remaining: 2.58s
244:	learn: 0.5185630	total: 835ms	remaining: 2.57s
245:	learn: 0.5183649	total: 838ms	remaining: 2.57s
246:	learn: 0.5182405	total: 841ms	remaining: 2.56s
247:	learn: 0.5181347	total: 844ms	remaining: 2.56s
248:	learn: 0.5180941	total: 848ms	remaining: 2.56s
249:	learn: 0.5179986	total: 851ms	remaining: 2.55s
250:	learn: 0.5177729	total: 854ms	remaining: 2.55s
251:	learn: 0.5175595	total: 857ms	remaining: 2.54s
252:	learn: 0.5173605	total: 861ms	remaining: 2.54s
253:	learn: 0.5172872	total: 864ms	remaining: 2.54s
254:	learn: 0.5171869	total: 868ms	remaining: 2.53s
255:	learn: 0.5171012	total: 871ms	remaining: 2.53s
256:	learn: 0.5170473	total: 875ms	remaining: 2.53s
257:	learn: 0.5169330	total: 878ms	remaining: 2.52s
258:	learn: 0.5168371	total: 882ms	remaining: 2.52s
259:	learn: 0.5167635	total: 885ms	remaining: 2.52s
260:	learn: 0.5165662	total: 889ms	remaining: 2.52s
261:	learn: 0.5164838	total: 893ms	remaining: 2.51s
262:	learn: 0.5164583	total: 896ms	remaining: 2.51s
263:	learn: 0.5163649	total: 899ms	remaining: 2.51s
264:	learn: 0.5162891	total: 903ms	remaining: 2.5s
265:	learn: 0.5162438	total: 906ms	remaining: 2.5s
266:	learn: 0.5161543	total: 909ms	remaining: 2.5s
267:	learn: 0.5160240	total: 912ms	remaining: 2.49s
268:	learn: 0.5157750	total: 916ms	remaining: 2.49s
269:	learn: 0.5156623	total: 919ms	remaining: 2.48s
270:	learn: 0.5156136	total: 922ms	remaining: 2.48s
271:	learn: 0.5154161	total: 926ms	remaining: 2.48s
272:	learn: 0.5153093	total: 929ms	remaining: 2.48s
273:	learn: 0.5152120	total: 933ms	remaining: 2.47s
274:	learn: 0.5151480	total: 936ms	remaining: 2.47s
275:	learn: 0.5150466	total: 938ms	remaining: 2.46s
276:	learn: 0.5149717	total: 943ms	remaining: 2.46s
277:	learn: 0.5149055	total: 952ms	remaining: 2.47s
278:	learn: 0.5146734	total: 956ms	remaining: 2.47s
279:	learn: 0.5145622	total: 959ms	remaining: 2.47s
280:	learn: 0.5145179	total: 963ms	remaining: 2.46s
281:	learn: 0.5143120	total: 967ms	remaining: 2.46s
282:	learn: 0.5142567	total: 970ms	remaining: 2.46s
283:	learn: 0.5141674	total: 975ms	remaining: 2.46s
284:	learn: 0.5138584	total: 978ms	remaining: 2.45s
285:	learn: 0.5136946	total: 982ms	remaining: 2.45s
286:	learn: 0.5135373	total: 986ms	remaining: 2.45s
287:	learn: 0.5134211	total: 989ms	remaining: 2.44s
288:	learn: 0.5133091	total: 993ms	remaining: 2.44s
289:	learn: 0.5132147	total: 997ms	remaining: 2.44s
290:	learn: 0.5131165	total: 1s	remaining: 2.44s
291:	learn: 0.5130303	total: 1s	remaining: 2.44s
292:	learn: 0.5129591	total: 1.01s	remaining: 2.43s
293:	learn: 0.5128433	total: 1.01s	remaining: 2.43s
294:	learn: 0.5127782	total: 1.01s	remaining: 2.42s
295:	learn: 0.5127264	total: 1.02s	remaining: 2.42s
296:	learn: 0.5126284	total: 1.02s	remaining: 2.42s
297:	learn: 0.5125577	total: 1.02s	remaining: 2.41s
298:	learn: 0.5124790	total: 1.03s	remaining: 2.41s
299:	learn: 0.5123628	total: 1.03s	remaining: 2.41s
300:	learn: 0.5123144	total: 1.03s	remaining: 2.4s
301:	learn: 0.5122488	total: 1.04s	remaining: 2.4s
302:	learn: 0.5122018	total: 1.04s	remaining: 2.4s
303:	learn: 0.5120993	total: 1.04s	remaining: 2.39s
304:	learn: 0.5119469	total: 1.05s	remaining: 2.39s
305:	learn: 0.5118851	total: 1.05s	remaining: 2.39s
306:	learn: 0.5118100	total: 1.06s	remaining: 2.39s
307:	learn: 0.5116833	total: 1.06s	remaining: 2.39s
308:	learn: 0.5115890	total: 1.07s	remaining: 2.38s
309:	learn: 0.5114555	total: 1.07s	remaining: 2.38s
310:	learn: 0.5113136	total: 1.07s	remaining: 2.38s
311:	learn: 0.5112220	total: 1.08s	remaining: 2.38s
312:	learn: 0.5110947	total: 1.08s	remaining: 2.37s
313:	learn: 0.5109252	total: 1.08s	remaining: 2.37s
314:	learn: 0.5108456	total: 1.09s	remaining: 2.37s
315:	learn: 0.5107625	total: 1.09s	remaining: 2.36s
316:	learn: 0.5106565	total: 1.09s	remaining: 2.36s
317:	learn: 0.5103883	total: 1.1s	remaining: 2.36s
318:	learn: 0.5102217	total: 1.1s	remaining: 2.35s
319:	learn: 0.5101590	total: 1.1s	remaining: 2.35s
320:	learn: 0.5100822	total: 1.11s	remaining: 2.35s
321:	learn: 0.5099999	total: 1.11s	remaining: 2.34s
322:	learn: 0.5099383	total: 1.12s	remaining: 2.34s
323:	learn: 0.5098506	total: 1.12s	remaining: 2.34s
324:	learn: 0.5097007	total: 1.12s	remaining: 2.33s
325:	learn: 0.5095294	total: 1.13s	remaining: 2.33s
326:	learn: 0.5094909	total: 1.13s	remaining: 2.33s
327:	learn: 0.5094469	total: 1.13s	remaining: 2.32s
328:	learn: 0.5093579	total: 1.14s	remaining: 2.32s
329:	learn: 0.5091998	total: 1.14s	remaining: 2.32s
330:	learn: 0.5090303	total: 1.14s	remaining: 2.31s
331:	learn: 0.5089854	total: 1.15s	remaining: 2.31s
332:	learn: 0.5087932	total: 1.15s	remaining: 2.31s
333:	learn: 0.5087195	total: 1.16s	remaining: 2.3s
334:	learn: 0.5085844	total: 1.16s	remaining: 2.3s
335:	learn: 0.5085201	total: 1.16s	remaining: 2.29s
336:	learn: 0.5084779	total: 1.17s	remaining: 2.29s
337:	learn: 0.5084452	total: 1.17s	remaining: 2.29s
338:	learn: 0.5083833	total: 1.17s	remaining: 2.29s
339:	learn: 0.5082780	total: 1.18s	remaining: 2.28s
340:	learn: 0.5081781	total: 1.18s	remaining: 2.28s
341:	learn: 0.5081241	total: 1.18s	remaining: 2.27s
342:	learn: 0.5080407	total: 1.19s	remaining: 2.27s
343:	learn: 0.5079481	total: 1.19s	remaining: 2.27s
344:	learn: 0.5078521	total: 1.19s	remaining: 2.27s
345:	learn: 0.5077417	total: 1.2s	remaining: 2.26s
346:	learn: 0.5076455	total: 1.2s	remaining: 2.26s
347:	learn: 0.5075013	total: 1.2s	remaining: 2.25s
348:	learn: 0.5074599	total: 1.21s	remaining: 2.25s
349:	learn: 0.5073286	total: 1.21s	remaining: 2.25s
350:	learn: 0.5072491	total: 1.21s	remaining: 2.25s
351:	learn: 0.5071282	total: 1.22s	remaining: 2.24s
352:	learn: 0.5071025	total: 1.22s	remaining: 2.24s
353:	learn: 0.5069892	total: 1.23s	remaining: 2.23s
354:	learn: 0.5069089	total: 1.23s	remaining: 2.23s
355:	learn: 0.5068609	total: 1.23s	remaining: 2.23s
356:	learn: 0.5068150	total: 1.24s	remaining: 2.23s
357:	learn: 0.5067168	total: 1.24s	remaining: 2.22s
358:	learn: 0.5066460	total: 1.24s	remaining: 2.22s
359:	learn: 0.5065638	total: 1.25s	remaining: 2.21s
360:	learn: 0.5063826	total: 1.25s	remaining: 2.21s
361:	learn: 0.5062679	total: 1.25s	remaining: 2.21s
362:	learn: 0.5061974	total: 1.26s	remaining: 2.21s
363:	learn: 0.5061007	total: 1.26s	remaining: 2.2s
364:	learn: 0.5060054	total: 1.26s	remaining: 2.2s
365:	learn: 0.5059738	total: 1.27s	remaining: 2.19s
366:	learn: 0.5059230	total: 1.27s	remaining: 2.19s
367:	learn: 0.5058569	total: 1.27s	remaining: 2.19s
368:	learn: 0.5057196	total: 1.28s	remaining: 2.18s
369:	learn: 0.5056482	total: 1.28s	remaining: 2.18s
370:	learn: 0.5055686	total: 1.28s	remaining: 2.18s
371:	learn: 0.5055230	total: 1.29s	remaining: 2.17s
372:	learn: 0.5054588	total: 1.29s	remaining: 2.17s
373:	learn: 0.5054096	total: 1.29s	remaining: 2.17s
374:	learn: 0.5052337	total: 1.3s	remaining: 2.16s
375:	learn: 0.5051835	total: 1.3s	remaining: 2.16s
376:	learn: 0.5051056	total: 1.3s	remaining: 2.16s
377:	learn: 0.5050269	total: 1.31s	remaining: 2.15s
378:	learn: 0.5049835	total: 1.31s	remaining: 2.15s
379:	learn: 0.5047542	total: 1.31s	remaining: 2.15s
380:	learn: 0.5046491	total: 1.32s	remaining: 2.14s
381:	learn: 0.5045834	total: 1.32s	remaining: 2.14s
382:	learn: 0.5044992	total: 1.32s	remaining: 2.13s
383:	learn: 0.5044166	total: 1.33s	remaining: 2.13s
384:	learn: 0.5044015	total: 1.33s	remaining: 2.13s
385:	learn: 0.5043303	total: 1.33s	remaining: 2.12s

2026/04/12 11:21:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:21:22 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:32:02 WARNING mlflow.sklearn.utils: RocCurveDisplay.from_estimator failed. The artifact training_roc_curve will not be recorded. Artifact error: Pipeline has none of the following attributes: predict_proba, decision_function.
2026/04/12 11:32:02 WARNING mlflow.sklearn.utils: PrecisionRecallDisplay.from_estimator failed. The artifact training_precision_recall_curve will not be recorded. Artifact error: Pipeline has none of the following attributes: predict_proba, decision_function.
2026/04/12 11:32:05 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run Ensamble de Votos at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/0476d317791f4b02a443543b030fd607
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

### Stacking

In [50]:
with mlflow.start_run(run_name = "Ensamble de Pilas") as run:

    
    algorithm1 = CatBoostClassifier()
    algorithm2 = XGBClassifier()
    algorithm3 = LGBMClassifier()

    voting_clf = StackingClassifier(
        estimators = [
            ("catboost", algorithm1),
            ("xgb", algorithm2),
            ("lgbm", algorithm3),
        ],
        final_estimator = RandomForestClassifier()
    )
    
    pipeline = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "mean")),
            ("stacking", voting_clf)
        ]
    )
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    _accuracy_score = accuracy_score(y_test, predictions)
    _f1_score = f1_score(y_test, predictions)
    
    mlflow.log_metrics(
        {
            "accuracy": _accuracy_score,
            "f1": _f1_score
        }
    )

2026/04/12 11:32:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

Learning rate set to 0.070218
0:	learn: 0.6738107	total: 4.71ms	remaining: 4.7s
1:	learn: 0.6577171	total: 7.61ms	remaining: 3.79s
2:	learn: 0.6435684	total: 11ms	remaining: 3.65s
3:	learn: 0.6321459	total: 14.2ms	remaining: 3.54s
4:	learn: 0.6222569	total: 17.3ms	remaining: 3.44s
5:	learn: 0.6135038	total: 20.9ms	remaining: 3.46s
6:	learn: 0.6061515	total: 24.1ms	remaining: 3.42s
7:	learn: 0.5998937	total: 27.5ms	remaining: 3.4s
8:	learn: 0.5941178	total: 30.6ms	remaining: 3.37s
9:	learn: 0.5893167	total: 34.2ms	remaining: 3.39s
10:	learn: 0.5856666	total: 37.2ms	remaining: 3.35s
11:	learn: 0.5821017	total: 40.2ms	remaining: 3.31s
12:	learn: 0.5786853	total: 43.3ms	remaining: 3.29s
13:	learn: 0.5756694	total: 46.7ms	remaining: 3.29s
14:	learn: 0.5733002	total: 50.3ms	remaining: 3.3s
15:	learn: 0.5706374	total: 53.7ms	remaining: 3.3s
16:	learn: 0.5683691	total: 57ms	remaining: 3.29s
17:	learn: 0.5667672	total: 60.4ms	remaining: 3.3s
18:	learn: 0.5653223	total: 63.3ms	remaining: 3.27s
19:	learn: 0.5641410	total: 66.7ms	remaining: 3.27s
20:	learn: 0.5631459	total: 70.5ms	remaining: 3.29s
21:	learn: 0.5618240	total: 73.7ms	remaining: 3.28s
22:	learn: 0.5608909	total: 77.1ms	remaining: 3.27s
23:	learn: 0.5599047	total: 80.1ms	remaining: 3.26s
24:	learn: 0.5586703	total: 83.1ms	remaining: 3.24s
25:	learn: 0.5582174	total: 86.3ms	remaining: 3.23s
26:	learn: 0.5573847	total: 89ms	remaining: 3.21s
27:	learn: 0.5568440	total: 92.7ms	remaining: 3.22s
28:	learn: 0.5559781	total: 96.1ms	remaining: 3.22s
29:	learn: 0.5551893	total: 99.3ms	remaining: 3.21s
30:	learn: 0.5546451	total: 103ms	remaining: 3.21s
31:	learn: 0.5543225	total: 106ms	remaining: 3.2s
32:	learn: 0.5540673	total: 109ms	remaining: 3.21s
33:	learn: 0.5535602	total: 112ms	remaining: 3.19s
34:	learn: 0.5533113	total: 116ms	remaining: 3.19s
35:	learn: 0.5529834	total: 119ms	remaining: 3.18s
36:	learn: 0.5523031	total: 122ms	remaining: 3.17s
37:	learn: 0.5515118	total: 125ms	remaining: 3.17s
38:	learn: 0.5508521	total: 128ms	remaining: 3.17s
39:	learn: 0.5506638	total: 131ms	remaining: 3.15s
40:	learn: 0.5503932	total: 135ms	remaining: 3.15s
41:	learn: 0.5501778	total: 138ms	remaining: 3.15s
42:	learn: 0.5497177	total: 141ms	remaining: 3.13s
43:	learn: 0.5494046	total: 144ms	remaining: 3.13s
44:	learn: 0.5489604	total: 148ms	remaining: 3.13s
45:	learn: 0.5487134	total: 151ms	remaining: 3.13s
46:	learn: 0.5483701	total: 154ms	remaining: 3.13s
47:	learn: 0.5479913	total: 158ms	remaining: 3.13s
48:	learn: 0.5476697	total: 161ms	remaining: 3.13s
49:	learn: 0.5473737	total: 164ms	remaining: 3.12s
50:	learn: 0.5472517	total: 168ms	remaining: 3.12s
51:	learn: 0.5468606	total: 171ms	remaining: 3.12s
52:	learn: 0.5466808	total: 175ms	remaining: 3.13s
53:	learn: 0.5463336	total: 178ms	remaining: 3.12s
54:	learn: 0.5460631	total: 182ms	remaining: 3.12s
55:	learn: 0.5460109	total: 185ms	remaining: 3.12s
56:	learn: 0.5454197	total: 188ms	remaining: 3.12s
57:	learn: 0.5451444	total: 192ms	remaining: 3.11s
58:	learn: 0.5450418	total: 195ms	remaining: 3.11s
59:	learn: 0.5448389	total: 199ms	remaining: 3.11s
60:	learn: 0.5446956	total: 202ms	remaining: 3.11s
61:	learn: 0.5442598	total: 206ms	remaining: 3.11s
62:	learn: 0.5439911	total: 209ms	remaining: 3.11s
63:	learn: 0.5439087	total: 212ms	remaining: 3.1s
64:	learn: 0.5436263	total: 215ms	remaining: 3.1s
65:	learn: 0.5435296	total: 219ms	remaining: 3.09s
66:	learn: 0.5434358	total: 222ms	remaining: 3.09s
67:	learn: 0.5433243	total: 225ms	remaining: 3.09s
68:	learn: 0.5429458	total: 229ms	remaining: 3.09s
69:	learn: 0.5428333	total: 232ms	remaining: 3.08s
70:	learn: 0.5426788	total: 235ms	remaining: 3.08s
71:	learn: 0.5425817	total: 238ms	remaining: 3.07s
72:	learn: 0.5421866	total: 242ms	remaining: 3.07s
73:	learn: 0.5420961	total: 245ms	remaining: 3.06s
74:	learn: 0.5420396	total: 248ms	remaining: 3.06s
75:	learn: 0.5418313	total: 252ms	remaining: 3.06s
76:	learn: 0.5416199	total: 255ms	remaining: 3.05s
77:	learn: 0.5414986	total: 258ms	remaining: 3.05s
78:	learn: 0.5412573	total: 261ms	remaining: 3.04s
79:	learn: 0.5411249	total: 264ms	remaining: 3.04s
80:	learn: 0.5408038	total: 268ms	remaining: 3.04s
81:	learn: 0.5406636	total: 271ms	remaining: 3.04s
82:	learn: 0.5404834	total: 275ms	remaining: 3.03s
83:	learn: 0.5403061	total: 278ms	remaining: 3.03s
84:	learn: 0.5402357	total: 281ms	remaining: 3.03s
85:	learn: 0.5397903	total: 285ms	remaining: 3.02s
86:	learn: 0.5395818	total: 288ms	remaining: 3.02s
87:	learn: 0.5395097	total: 291ms	remaining: 3.02s
88:	learn: 0.5391467	total: 295ms	remaining: 3.02s
89:	learn: 0.5390145	total: 298ms	remaining: 3.01s
90:	learn: 0.5386672	total: 301ms	remaining: 3.01s
91:	learn: 0.5384415	total: 304ms	remaining: 3s
92:	learn: 0.5382380	total: 308ms	remaining: 3s
93:	learn: 0.5381863	total: 310ms	remaining: 2.99s
94:	learn: 0.5380044	total: 314ms	remaining: 2.99s
95:	learn: 0.5379459	total: 317ms	remaining: 2.98s
96:	learn: 0.5378191	total: 320ms	remaining: 2.98s
97:	learn: 0.5377368	total: 324ms	remaining: 2.98s
98:	learn: 0.5376021	total: 327ms	remaining: 2.98s
99:	learn: 0.5374685	total: 331ms	remaining: 2.98s
100:	learn: 0.5373199	total: 334ms	remaining: 2.98s
101:	learn: 0.5372167	total: 338ms	remaining: 2.97s
102:	learn: 0.5370365	total: 341ms	remaining: 2.97s
103:	learn: 0.5369342	total: 344ms	remaining: 2.97s
104:	learn: 0.5368719	total: 348ms	remaining: 2.96s
105:	learn: 0.5367660	total: 351ms	remaining: 2.96s
106:	learn: 0.5366967	total: 354ms	remaining: 2.96s
107:	learn: 0.5364545	total: 357ms	remaining: 2.95s
108:	learn: 0.5362580	total: 361ms	remaining: 2.95s
109:	learn: 0.5361734	total: 364ms	remaining: 2.94s
110:	learn: 0.5359874	total: 367ms	remaining: 2.94s
111:	learn: 0.5359660	total: 370ms	remaining: 2.94s
112:	learn: 0.5357150	total: 374ms	remaining: 2.93s
113:	learn: 0.5355980	total: 377ms	remaining: 2.93s
114:	learn: 0.5354281	total: 380ms	remaining: 2.93s
115:	learn: 0.5353798	total: 383ms	remaining: 2.92s
116:	learn: 0.5352257	total: 387ms	remaining: 2.92s
117:	learn: 0.5351851	total: 390ms	remaining: 2.92s
118:	learn: 0.5349484	total: 393ms	remaining: 2.91s
119:	learn: 0.5347588	total: 397ms	remaining: 2.91s
120:	learn: 0.5345829	total: 400ms	remaining: 2.91s
121:	learn: 0.5344015	total: 404ms	remaining: 2.91s
122:	learn: 0.5341694	total: 408ms	remaining: 2.91s
123:	learn: 0.5339794	total: 411ms	remaining: 2.9s
124:	learn: 0.5339310	total: 414ms	remaining: 2.9s
125:	learn: 0.5338830	total: 418ms	remaining: 2.9s
126:	learn: 0.5337809	total: 421ms	remaining: 2.89s
127:	learn: 0.5337063	total: 424ms	remaining: 2.89s
128:	learn: 0.5336765	total: 428ms	remaining: 2.89s
129:	learn: 0.5336251	total: 431ms	remaining: 2.88s
130:	learn: 0.5333297	total: 434ms	remaining: 2.88s
131:	learn: 0.5332695	total: 438ms	remaining: 2.88s
132:	learn: 0.5329141	total: 441ms	remaining: 2.88s
133:	learn: 0.5328899	total: 444ms	remaining: 2.87s
134:	learn: 0.5328678	total: 447ms	remaining: 2.87s
135:	learn: 0.5327968	total: 451ms	remaining: 2.86s
136:	learn: 0.5326215	total: 454ms	remaining: 2.86s
137:	learn: 0.5325836	total: 457ms	remaining: 2.85s
138:	learn: 0.5324896	total: 461ms	remaining: 2.85s
139:	learn: 0.5324247	total: 464ms	remaining: 2.85s
140:	learn: 0.5323806	total: 467ms	remaining: 2.85s
141:	learn: 0.5321852	total: 470ms	remaining: 2.84s
142:	learn: 0.5320983	total: 474ms	remaining: 2.84s
143:	learn: 0.5318958	total: 477ms	remaining: 2.84s
144:	learn: 0.5318458	total: 480ms	remaining: 2.83s
145:	learn: 0.5317970	total: 484ms	remaining: 2.83s
146:	learn: 0.5315150	total: 487ms	remaining: 2.83s
147:	learn: 0.5312856	total: 490ms	remaining: 2.82s
148:	learn: 0.5309869	total: 493ms	remaining: 2.82s
149:	learn: 0.5308861	total: 497ms	remaining: 2.82s
150:	learn: 0.5308428	total: 500ms	remaining: 2.81s
151:	learn: 0.5307694	total: 504ms	remaining: 2.81s
152:	learn: 0.5307060	total: 507ms	remaining: 2.81s
153:	learn: 0.5306848	total: 510ms	remaining: 2.8s
154:	learn: 0.5304849	total: 514ms	remaining: 2.8s
155:	learn: 0.5303018	total: 517ms	remaining: 2.8s
156:	learn: 0.5300803	total: 521ms	remaining: 2.8s
157:	learn: 0.5299034	total: 524ms	remaining: 2.79s
158:	learn: 0.5296628	total: 528ms	remaining: 2.79s
159:	learn: 0.5295286	total: 531ms	remaining: 2.79s
160:	learn: 0.5294176	total: 534ms	remaining: 2.78s
161:	learn: 0.5292346	total: 538ms	remaining: 2.78s
162:	learn: 0.5291623	total: 541ms	remaining: 2.78s
163:	learn: 0.5289835	total: 544ms	remaining: 2.77s
164:	learn: 0.5289236	total: 548ms	remaining: 2.77s
165:	learn: 0.5288327	total: 551ms	remaining: 2.77s
166:	learn: 0.5286664	total: 554ms	remaining: 2.76s
167:	learn: 0.5285878	total: 557ms	remaining: 2.76s
168:	learn: 0.5285416	total: 560ms	remaining: 2.75s
169:	learn: 0.5283516	total: 563ms	remaining: 2.75s
170:	learn: 0.5282968	total: 567ms	remaining: 2.75s
171:	learn: 0.5282452	total: 570ms	remaining: 2.74s
172:	learn: 0.5280301	total: 573ms	remaining: 2.74s
173:	learn: 0.5278876	total: 576ms	remaining: 2.73s
174:	learn: 0.5276559	total: 580ms	remaining: 2.73s
175:	learn: 0.5275279	total: 583ms	remaining: 2.73s
176:	learn: 0.5274036	total: 586ms	remaining: 2.73s
177:	learn: 0.5272711	total: 589ms	remaining: 2.72s
178:	learn: 0.5270226	total: 592ms	remaining: 2.72s
179:	learn: 0.5269950	total: 595ms	remaining: 2.71s
180:	learn: 0.5268308	total: 599ms	remaining: 2.71s
181:	learn: 0.5266779	total: 602ms	remaining: 2.71s
182:	learn: 0.5264732	total: 606ms	remaining: 2.7s
183:	learn: 0.5263815	total: 609ms	remaining: 2.7s
184:	learn: 0.5261524	total: 612ms	remaining: 2.7s
185:	learn: 0.5260501	total: 616ms	remaining: 2.69s
186:	learn: 0.5258866	total: 619ms	remaining: 2.69s
187:	learn: 0.5256008	total: 622ms	remaining: 2.69s
188:	learn: 0.5254093	total: 626ms	remaining: 2.68s
189:	learn: 0.5252663	total: 629ms	remaining: 2.68s
190:	learn: 0.5251440	total: 632ms	remaining: 2.68s
191:	learn: 0.5250158	total: 635ms	remaining: 2.67s
192:	learn: 0.5249114	total: 638ms	remaining: 2.67s
193:	learn: 0.5247453	total: 642ms	remaining: 2.67s
194:	learn: 0.5246752	total: 645ms	remaining: 2.66s
195:	learn: 0.5244250	total: 649ms	remaining: 2.66s
196:	learn: 0.5243375	total: 652ms	remaining: 2.66s
197:	learn: 0.5242522	total: 655ms	remaining: 2.65s
198:	learn: 0.5241577	total: 658ms	remaining: 2.65s
199:	learn: 0.5240787	total: 662ms	remaining: 2.65s
200:	learn: 0.5239741	total: 665ms	remaining: 2.64s
201:	learn: 0.5238183	total: 668ms	remaining: 2.64s
202:	learn: 0.5236766	total: 671ms	remaining: 2.64s
203:	learn: 0.5235352	total: 675ms	remaining: 2.63s
204:	learn: 0.5233945	total: 678ms	remaining: 2.63s
205:	learn: 0.5232546	total: 682ms	remaining: 2.63s
206:	learn: 0.5230454	total: 685ms	remaining: 2.62s
207:	learn: 0.5229536	total: 688ms	remaining: 2.62s
208:	learn: 0.5227056	total: 692ms	remaining: 2.62s
209:	learn: 0.5225294	total: 695ms	remaining: 2.61s
210:	learn: 0.5224116	total: 699ms	remaining: 2.61s
211:	learn: 0.5221831	total: 702ms	remaining: 2.61s
212:	learn: 0.5220323	total: 705ms	remaining: 2.6s
213:	learn: 0.5219855	total: 708ms	remaining: 2.6s
214:	learn: 0.5219285	total: 712ms	remaining: 2.6s
215:	learn: 0.5218675	total: 715ms	remaining: 2.59s
216:	learn: 0.5216811	total: 718ms	remaining: 2.59s
217:	learn: 0.5215916	total: 721ms	remaining: 2.59s
218:	learn: 0.5214674	total: 725ms	remaining: 2.58s
219:	learn: 0.5213997	total: 728ms	remaining: 2.58s
220:	learn: 0.5212905	total: 731ms	remaining: 2.58s
221:	learn: 0.5211581	total: 735ms	remaining: 2.58s
222:	learn: 0.5210843	total: 738ms	remaining: 2.57s
223:	learn: 0.5209140	total: 742ms	remaining: 2.57s
224:	learn: 0.5208204	total: 745ms	remaining: 2.57s
225:	learn: 0.5206668	total: 748ms	remaining: 2.56s
226:	learn: 0.5204637	total: 752ms	remaining: 2.56s
227:	learn: 0.5203735	total: 755ms	remaining: 2.56s
228:	learn: 0.5202461	total: 759ms	remaining: 2.55s
229:	learn: 0.5201411	total: 762ms	remaining: 2.55s
230:	learn: 0.5200951	total: 765ms	remaining: 2.55s
231:	learn: 0.5199251	total: 769ms	remaining: 2.54s
232:	learn: 0.5196606	total: 772ms	remaining: 2.54s
233:	learn: 0.5195978	total: 776ms	remaining: 2.54s
234:	learn: 0.5195306	total: 779ms	remaining: 2.53s
235:	learn: 0.5194868	total: 782ms	remaining: 2.53s
236:	learn: 0.5193511	total: 785ms	remaining: 2.53s
237:	learn: 0.5192522	total: 789ms	remaining: 2.52s
238:	learn: 0.5191186	total: 792ms	remaining: 2.52s
239:	learn: 0.5189888	total: 795ms	remaining: 2.52s
240:	learn: 0.5188789	total: 798ms	remaining: 2.51s
241:	learn: 0.5188263	total: 802ms	remaining: 2.51s
242:	learn: 0.5187082	total: 805ms	remaining: 2.51s
243:	learn: 0.5186290	total: 808ms	remaining: 2.5s
244:	learn: 0.5185630	total: 812ms	remaining: 2.5s
245:	learn: 0.5183649	total: 815ms	remaining: 2.5s
246:	learn: 0.5182405	total: 818ms	remaining: 2.49s
247:	learn: 0.5181347	total: 821ms	remaining: 2.49s
248:	learn: 0.5180941	total: 825ms	remaining: 2.49s
249:	learn: 0.5179986	total: 828ms	remaining: 2.48s
250:	learn: 0.5177729	total: 831ms	remaining: 2.48s
251:	learn: 0.5175595	total: 835ms	remaining: 2.48s
252:	learn: 0.5173605	total: 838ms	remaining: 2.47s
253:	learn: 0.5172872	total: 841ms	remaining: 2.47s
254:	learn: 0.5171869	total: 845ms	remaining: 2.47s
255:	learn: 0.5171012	total: 848ms	remaining: 2.46s
256:	learn: 0.5170473	total: 851ms	remaining: 2.46s
257:	learn: 0.5169330	total: 855ms	remaining: 2.46s
258:	learn: 0.5168371	total: 858ms	remaining: 2.45s
259:	learn: 0.5167635	total: 861ms	remaining: 2.45s
260:	learn: 0.5165662	total: 864ms	remaining: 2.45s
261:	learn: 0.5164838	total: 868ms	remaining: 2.44s
262:	learn: 0.5164583	total: 871ms	remaining: 2.44s
263:	learn: 0.5163649	total: 874ms	remaining: 2.44s
264:	learn: 0.5162891	total: 877ms	remaining: 2.43s
265:	learn: 0.5162438	total: 880ms	remaining: 2.43s
266:	learn: 0.5161543	total: 884ms	remaining: 2.42s
267:	learn: 0.5160240	total: 887ms	remaining: 2.42s
268:	learn: 0.5157750	total: 891ms	remaining: 2.42s
269:	learn: 0.5156623	total: 894ms	remaining: 2.42s
270:	learn: 0.5156136	total: 897ms	remaining: 2.41s
271:	learn: 0.5154161	total: 901ms	remaining: 2.41s
272:	learn: 0.5153093	total: 904ms	remaining: 2.41s
273:	learn: 0.5152120	total: 908ms	remaining: 2.4s
274:	learn: 0.5151480	total: 911ms	remaining: 2.4s
275:	learn: 0.5150466	total: 914ms	remaining: 2.4s
276:	learn: 0.5149717	total: 916ms	remaining: 2.39s
277:	learn: 0.5149055	total: 927ms	remaining: 2.41s
278:	learn: 0.5146734	total: 930ms	remaining: 2.4s
279:	learn: 0.5145622	total: 934ms	remaining: 2.4s
280:	learn: 0.5145179	total: 937ms	remaining: 2.4s
281:	learn: 0.5143120	total: 940ms	remaining: 2.39s
282:	learn: 0.5142567	total: 944ms	remaining: 2.39s
283:	learn: 0.5141674	total: 947ms	remaining: 2.39s
284:	learn: 0.5138584	total: 950ms	remaining: 2.38s
285:	learn: 0.5136946	total: 954ms	remaining: 2.38s
286:	learn: 0.5135373	total: 957ms	remaining: 2.38s
287:	learn: 0.5134211	total: 961ms	remaining: 2.37s
288:	learn: 0.5133091	total: 964ms	remaining: 2.37s
289:	learn: 0.5132147	total: 967ms	remaining: 2.37s
290:	learn: 0.5131165	total: 971ms	remaining: 2.37s
291:	learn: 0.5130303	total: 974ms	remaining: 2.36s
292:	learn: 0.5129591	total: 977ms	remaining: 2.36s
293:	learn: 0.5128433	total: 981ms	remaining: 2.35s
294:	learn: 0.5127782	total: 984ms	remaining: 2.35s
295:	learn: 0.5127264	total: 987ms	remaining: 2.35s
296:	learn: 0.5126284	total: 990ms	remaining: 2.34s
297:	learn: 0.5125577	total: 994ms	remaining: 2.34s
298:	learn: 0.5124790	total: 997ms	remaining: 2.34s
299:	learn: 0.5123628	total: 1000ms	remaining: 2.33s
300:	learn: 0.5123144	total: 1s	remaining: 2.33s
301:	learn: 0.5122488	total: 1.01s	remaining: 2.33s
302:	learn: 0.5122018	total: 1.01s	remaining: 2.32s
303:	learn: 0.5120993	total: 1.01s	remaining: 2.32s
304:	learn: 0.5119469	total: 1.02s	remaining: 2.32s
305:	learn: 0.5118851	total: 1.02s	remaining: 2.31s
306:	learn: 0.5118100	total: 1.02s	remaining: 2.31s
307:	learn: 0.5116833	total: 1.04s	remaining: 2.33s
308:	learn: 0.5115890	total: 1.04s	remaining: 2.33s
309:	learn: 0.5114555	total: 1.04s	remaining: 2.32s
310:	learn: 0.5113136	total: 1.05s	remaining: 2.32s
311:	learn: 0.5112220	total: 1.05s	remaining: 2.32s
312:	learn: 0.5110947	total: 1.05s	remaining: 2.31s
313:	learn: 0.5109252	total: 1.06s	remaining: 2.31s
314:	learn: 0.5108456	total: 1.06s	remaining: 2.31s
315:	learn: 0.5107625	total: 1.06s	remaining: 2.3s
316:	learn: 0.5106565	total: 1.07s	remaining: 2.3s
317:	learn: 0.5103883	total: 1.07s	remaining: 2.3s
318:	learn: 0.5102217	total: 1.07s	remaining: 2.29s
319:	learn: 0.5101590	total: 1.08s	remaining: 2.29s
320:	learn: 0.5100822	total: 1.08s	remaining: 2.29s
321:	learn: 0.5099999	total: 1.08s	remaining: 2.28s
322:	learn: 0.5099383	total: 1.09s	remaining: 2.28s
323:	learn: 0.5098506	total: 1.09s	remaining: 2.28s
324:	learn: 0.5097007	total: 1.09s	remaining: 2.27s
325:	learn: 0.5095294	total: 1.1s	remaining: 2.27s
326:	learn: 0.5094909	total: 1.1s	remaining: 2.27s
327:	learn: 0.5094469	total: 1.1s	remaining: 2.26s
328:	learn: 0.5093579	total: 1.11s	remaining: 2.26s
329:	learn: 0.5091998	total: 1.11s	remaining: 2.26s
330:	learn: 0.5090303	total: 1.11s	remaining: 2.25s
331:	learn: 0.5089854	total: 1.12s	remaining: 2.25s
332:	learn: 0.5087932	total: 1.12s	remaining: 2.25s
333:	learn: 0.5087195	total: 1.12s	remaining: 2.24s
334:	learn: 0.5085844	total: 1.13s	remaining: 2.24s
335:	learn: 0.5085201	total: 1.13s	remaining: 2.23s
336:	learn: 0.5084779	total: 1.13s	remaining: 2.23s
337:	learn: 0.5084452	total: 1.14s	remaining: 2.23s
338:	learn: 0.5083833	total: 1.14s	remaining: 2.22s
339:	learn: 0.5082780	total: 1.14s	remaining: 2.22s
340:	learn: 0.5081781	total: 1.15s	remaining: 2.22s
341:	learn: 0.5081241	total: 1.15s	remaining: 2.21s
342:	learn: 0.5080407	total: 1.15s	remaining: 2.21s
343:	learn: 0.5079481	total: 1.16s	remaining: 2.21s
344:	learn: 0.5078521	total: 1.16s	remaining: 2.2s
345:	learn: 0.5077417	total: 1.16s	remaining: 2.2s
346:	learn: 0.5076455	total: 1.17s	remaining: 2.19s
347:	learn: 0.5075013	total: 1.17s	remaining: 2.19s
348:	learn: 0.5074599	total: 1.17s	remaining: 2.19s
349:	learn: 0.5073286	total: 1.18s	remaining: 2.18s
350:	learn: 0.5072491	total: 1.18s	remaining: 2.18s
351:	learn: 0.5071282	total: 1.18s	remaining: 2.18s
352:	learn: 0.5071025	total: 1.19s	remaining: 2.17s
353:	learn: 0.5069892	total: 1.19s	remaining: 2.17s
354:	learn: 0.5069089	total: 1.19s	remaining: 2.17s
355:	learn: 0.5068609	total: 1.2s	remaining: 2.17s
356:	learn: 0.5068150	total: 1.2s	remaining: 2.16s
357:	learn: 0.5067168	total: 1.2s	remaining: 2.16s
358:	learn: 0.5066460	total: 1.21s	remaining: 2.15s
359:	learn: 0.5065638	total: 1.21s	remaining: 2.15s
360:	learn: 0.5063826	total: 1.21s	remaining: 2.15s
361:	learn: 0.5062679	total: 1.22s	remaining: 2.15s
362:	learn: 0.5061974	total: 1.22s	remaining: 2.14s
363:	learn: 0.5061007	total: 1.22s	remaining: 2.14s
364:	learn: 0.5060054	total: 1.23s	remaining: 2.13s
365:	learn: 0.5059738	total: 1.23s	remaining: 2.13s
366:	learn: 0.5059230	total: 1.23s	remaining: 2.13s
367:	learn: 0.5058569	total: 1.24s	remaining: 2.12s
368:	learn: 0.5057196	total: 1.24s	remaining: 2.12s
369:	learn: 0.5056482	total: 1.24s	remaining: 2.12s
370:	learn: 0.5055686	total: 1.25s	remaining: 2.11s
371:	learn: 0.5055230	total: 1.25s	remaining: 2.11s
372:	learn: 0.5054588	total: 1.25s	remaining: 2.11s
373:	learn: 0.5054096	total: 1.26s	remaining: 2.1s
374:	learn: 0.5052337	total: 1.26s	remaining: 2.1s
375:	learn: 0.5051835	total: 1.26s	remaining: 2.1s
376:	learn: 0.5051056	total: 1.27s	remaining: 2.09s
377:	learn: 0.5050269	total: 1.27s	remaining: 2.09s
378:	learn: 0.5049835	total: 1.27s	remaining: 2.09s
379:	learn: 0.5047542	total: 1.28s	remaining: 2.08s
380:	learn: 0.5046491	total: 1.28s	remaining: 2.08s
381:	learn: 0.5045834	total: 1.28s	remaining: 2.08s
382:	learn: 0.5044992	total: 1.29s	remaining: 2.07s
383:	learn: 0.5044166	total: 1.29s	remaining: 2.07s
384:	learn: 0.5044015	total: 1.29s	remaining: 2.06s
385:	learn: 0.5043303	total: 1.3s	remaining: 2.06s

2026/04/12 11:32:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/04/12 11:32:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/04/12 11:40:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/opt/miniconda3/envs/ciencia-de-datos/lib/python3.11/site-packages/mlflow/types/utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

🏃 View run Ensamble de Pilas at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2/runs/6e368bf3784a4a91bcb695dec009025c
🧪 View experiment at: https://dagshub.com/davidrodriguez2712/ml-2-modulo.mlflow/#/experiments/2

In [33]:
mlflow.create_experiment("DSRP - Booking Clase 14 Julio - Con mas variables")

'2'

In [34]:
mlflow.set_experiment("DSRP - Booking Clase 14 Julio - Con mas variables")

<Experiment: artifact_location='mlflow-artifacts:/00d5fb7c83b14b4d8e2727d8b811cfa1', creation_time=1776009501288, experiment_id='2', last_update_time=1776009501288, lifecycle_stage='active', name='DSRP - Booking Clase 14 Julio - Con mas variables', tags={}, trace_location=None, workspace='default'>