In [39]:
import pandas as pd
import numpy as np
import uuid
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA
from loguru import logger

In [4]:
raw_data = pd.read_csv("../data/raw/hotel_bookings.csv")

### Train - Test Split

In [28]:
TRAIN_SIZE = round(raw_data.shape[0] * 0.8)
TEST_SIZE = raw_data.shape[0] - TRAIN_SIZE

In [29]:
train_indices = raw_data.sample(TRAIN_SIZE).index

In [30]:
test_indices = [i for i in raw_data.index if i not in train_indices]

In [31]:
train_raw_data = raw_data.iloc[train_indices]
test_raw_data = raw_data.iloc[test_indices]

In [33]:
raw_data

               hotel  is_canceled  ...  reservation_status  reservation_status_date
0       Resort Hotel            0  ...           Check-Out               2015-07-01
1       Resort Hotel            0  ...           Check-Out               2015-07-01
2       Resort Hotel            0  ...           Check-Out               2015-07-02
3       Resort Hotel            0  ...           Check-Out               2015-07-02
4       Resort Hotel            0  ...           Check-Out               2015-07-03
...              ...          ...  ...                 ...                      ...
119385    City Hotel            0  ...           Check-Out               2017-09-06
119386    City Hotel            0  ...           Check-Out               2017-09-07
119387    City Hotel            0  ...           Check-Out               2017-09-07
119388    City Hotel            0  ...           Check-Out               2017-09-07
119389    City Hotel            0  ...           Check-Out               2017-09-07

[119390 rows x 32 columns]

In [32]:
train_raw_data

               hotel  is_canceled  ...  reservation_status  reservation_status_date
66009     City Hotel            1  ...            Canceled               2016-07-09
97040     City Hotel            0  ...           Check-Out               2016-09-12
104813    City Hotel            0  ...           Check-Out               2017-01-23
97668     City Hotel            0  ...           Check-Out               2016-09-19
79631     City Hotel            0  ...           Check-Out               2015-10-31
...              ...          ...  ...                 ...                      ...
101618    City Hotel            0  ...           Check-Out               2016-11-15
12175   Resort Hotel            1  ...            Canceled               2017-02-01
40565     City Hotel            1  ...            Canceled               2015-07-07
10662   Resort Hotel            1  ...            Canceled               2016-09-29
1484    Resort Hotel            0  ...           Check-Out               2015-09-11

[95512 rows x 32 columns]

In [36]:
train_raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95512 entries, 66009 to 1484
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           95512 non-null  object
 1   is_canceled                     95512 non-null  int64
 2   lead_time                       95512 non-null  int64
 3   arrival_date_year               95512 non-null  int64
 4   arrival_date_month              95512 non-null  object
 5   arrival_date_week_number        95512 non-null  int64
 6   arrival_date_day_of_month       95512 non-null  int64
 7   stays_in_weekend_nights         95512 non-null  int64
 8   stays_in_week_nights            95512 non-null  int64
 9   adults                          95512 non-null  int64
 10  children                        95509 non-null  float64
 11  babies                          95512 non-null  int64
 12  meal                            95512 non-null  object
 13  country                         95121 non-null  object
 14  market_segment                  95512 non-null  object
 15  distribution_channel            95512 non-null  object
 16  is_repeated_guest               95512 non-null  int64
 17  previous_cancellations          95512 non-null  int64
 18  previous_bookings_not_canceled  95512 non-null  int64
 19  reserved_room_type              95512 non-null  object
 20  assigned_room_type              95512 non-null  object
 21  booking_changes                 95512 non-null  int64
 22  deposit_type                    95512 non-null  object
 23  agent                           82520 non-null  float64
 24  company                         5370 non-null   float64
 25  days_in_waiting_list            95512 non-null  int64
 26  customer_type                   95512 non-null  object
 27  adr                             95512 non-null  float64
 28  required_car_parking_spaces     95512 non-null  int64
 29  total_of_special_requests       95512 non-null  int64
 30  reservation_status              95512 non-null  object
 31  reservation_status_date         95512 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 24.0+ MB

In [37]:
train_raw_data.describe()

        is_canceled  ...  total_of_special_requests
count  95512.000000  ...               95512.000000
mean       0.369985  ...                   0.571960
std        0.482803  ...                   0.793128
min        0.000000  ...                   0.000000
25%        0.000000  ...                   0.000000
50%        0.000000  ...                   0.000000
75%        1.000000  ...                   1.000000
max        1.000000  ...                   5.000000

[8 rows x 20 columns]

#### Encoding

In [41]:
train_raw_data["hotel"].value_counts()

hotel
City Hotel      63549
Resort Hotel    31963
Name: count, dtype: int64

In [47]:
encoder = OneHotEncoder() # primer encoder
encoded = encoder.fit_transform(train_raw_data[["hotel"]])
encoder.categories_[0]

array(['City Hotel', 'Resort Hotel'], dtype=object)

In [42]:
train_raw_data["market_segment"].value_counts()

market_segment
Online TA        45242
Offline TA/TO    19334
Groups           15794
Direct           10157
Corporate         4195
Complementary      596
Aviation           193
Undefined            1
Name: count, dtype: int64

In [54]:
train_raw_data["lead_time"]

66009     280
97040     277
104813     60
97668     315
79631       5
         ...
101618    116
12175     247
40565     130
10662     182
1484       68
Name: lead_time, Length: 95512, dtype: int64

In [79]:
class FeatureEngineeringProcessor:
    def __init__(self, raw_data: pd.DataFrame, pipeline_name: str) -> None:
        self.raw_data = raw_data
        self.pipeline_name = pipeline_name

    def impute_scale(self, n_components: int = 2) -> pd.DataFrame:
        """Pipeline que imputa variables numéricas y luego las escala,
        para finalmente Aplicar PCA y quedarse con N componentes principales"""
        numeric_cols = [
            "lead_time",
            "children",
            "adults",
            "babies",
            "adr"
        ]
        pipe = Pipeline(
            steps = [
                ("imputer_mean", SimpleImputer(strategy = "mean")),
                ("std_scaling", StandardScaler()),
                ("pca", PCA(n_components = n_components))
            ]
        )
        return pd.DataFrame(
            pipe.fit_transform(self.raw_data[numeric_cols]),
            columns = ["pc1", "pc2"]
        )

    def encode_categoricals(self) -> pd.DataFrame:
        encoded_vars = []
        for var in ["hotel", "market_segment", "reserved_room_type"]:
            logger.info(f"Codificando con OHE {var}")
            encoder = OneHotEncoder()
            encoded = encoder.fit_transform(self.raw_data[[var]]).toarray()
            cols = [f"{var}_{col}" for col in encoder.categories_[0]]
            _dataframe = pd.DataFrame(
                encoded,
                columns = cols
            )
            encoded_vars.append(_dataframe)
        return pd.concat(encoded_vars, axis = 1)
    
    def run(self) -> pd.DataFrame:
        # aca pondremos nuestro código
        logger.info(f"Inicializando Pipeline {self.pipeline_name}")
        
        categorical = self.encode_categoricals()
        numerics = self.impute_scale()

        modeling_dataset = pd.concat([categorical, numerics], axis = 1)
        # Dataset Previo al pipeline
        pipe = Pipeline(
            steps = [
                ("feature_selection", VarianceThreshold()),
                ("scaling_robust", RobustScaler())
            ]
        )
        
        return pd.DataFrame(
            pipe.fit_transform(modeling_dataset),
            columns = modeling_dataset.columns # si el VarianceThreshold elimina, ten cuidado
        )

In [82]:
train_processor = FeatureEngineeringProcessor(
    raw_data= train_raw_data,
    pipeline_name= "DSRP MLE2 Feature Engineering - TRAIN"
)
train_processor.run()

2026-02-15 07:15:59.785 | INFO     | __main__:run:44 - Inicializando Pipeline DSRP MLE2 Feature Engineering - TRAIN
2026-02-15 07:15:59.786 | INFO     | __main__:encode_categoricals:31 - Codificando con OHE hotel
2026-02-15 07:15:59.803 | INFO     | __main__:encode_categoricals:31 - Codificando con OHE market_segment
2026-02-15 07:15:59.816 | INFO     | __main__:encode_categoricals:31 - Codificando con OHE reserved_room_type

       hotel_City Hotel  hotel_Resort Hotel  ...       pc1       pc2
0                   0.0                 0.0  ...  1.847034  0.815314
1                   0.0                 0.0  ... -0.089553  1.448746
2                   0.0                 0.0  ...  1.162679 -1.184098
3                   0.0                 0.0  ... -0.446109  1.714808
4                   0.0                 0.0  ...  0.691145 -0.342293
...                 ...                 ...  ...       ...       ...
95507               0.0                 0.0  ...  0.215887  0.398638
95508              -1.0                 1.0  ... -0.315994  1.271213
95509               0.0                 0.0  ... -0.201688  0.514983
95510              -1.0                 1.0  ... -0.672252  0.877957
95511              -1.0                 1.0  ...  0.347195  0.082986

[95512 rows x 22 columns]

In [83]:
test_processor = FeatureEngineeringProcessor(
    raw_data= test_raw_data,
    pipeline_name= "DSRP MLE2 Feature Engineering - TEST"
)
test_processor.run()

2026-02-15 07:16:10.149 | INFO     | __main__:run:44 - Inicializando Pipeline DSRP MLE2 Feature Engineering - TEST
2026-02-15 07:16:10.150 | INFO     | __main__:encode_categoricals:31 - Codificando con OHE hotel
2026-02-15 07:16:10.157 | INFO     | __main__:encode_categoricals:31 - Codificando con OHE market_segment
2026-02-15 07:16:10.161 | INFO     | __main__:encode_categoricals:31 - Codificando con OHE reserved_room_type

       hotel_City Hotel  hotel_Resort Hotel  ...       pc1       pc2
0                  -1.0                 1.0  ... -1.279465  1.965921
1                  -1.0                 1.0  ... -1.326891  4.466729
2                  -1.0                 1.0  ...  0.141889 -0.253324
3                  -1.0                 1.0  ...  0.270485 -0.355058
4                  -1.0                 1.0  ...  0.121303  0.090014
...                 ...                 ...  ...       ...       ...
23873               0.0                 0.0  ... -1.098300 -0.136923
23874               0.0                 0.0  ...  2.692745  1.466466
23875               0.0                 0.0  ...  0.741137 -0.125605
23876               0.0                 0.0  ...  0.981503 -0.213599
23877               0.0                 0.0  ...  0.869170  0.878504

[23878 rows x 22 columns]